const rows = [
  ["Genesis", "Génesis", "genesis", "01", "Gen"], ["Exodus", "Éxodo", "exodo", "02", "Exo"], ["Leviticus", "Levítico", "levitico", "03", "Lev"], ["Numbers", "Números", "numeros", "04", "Num"], ["Deuteronomy", "Deuteronomio", "deuteronomio", "05", "Deu"], ["Joshua", "Josué", "josue", "06", "Jos"], ["Judges", "Jueces", "jueces", "07", "Jud"], ["Ruth", "Rut", "rut", "08", "Rut"], ["1 Samuel", "1 Samuel", "1samuel", "09", "1Sa"], ["2 Samuel", "2 Samuel", "2samuel", "10", "2Sa"], ["1 Kings", "1 Reyes", "1reyes", "11", "1Ki"], ["2 Kings", "2 Reyes", "2reyes", "12", "2Ki"], ["1 Chronicles", "1 Crónicas", "1cronicas", "13", "1Ch"], ["2 Chronicles", "2 Crónicas", "2cronicas", "14", "2Ch"], ["Ezra", "Esdras", "esdras", "15", "Ezr"], ["Nehemiah", "Nehemías", "nehemias", "16", "Neh"], ["Esther", "Ester", "ester", "17", "Est"], ["Job", "Job", "job", "18", "Job"], ["Psalms", "Salmos", "salmos", "19", "Psa"], ["Proverbs", "Proverbios", "proverbios", "20", "Pro"], ["Ecclesiastes", "Eclesiastés", "eclesiastes", "21", "Ecc"], ["Song of Songs", "Cantares", "cantares", "22", "Sng"], ["Isaiah", "Isaías", "isaias", "23", "Isa"], ["Jeremiah", "Jeremías", "jeremias", "24", "Jer"], ["Lamentations", "Lamentaciones", "lamentaciones", "25", "Lam"], ["Ezekiel", "Ezequiel", "ezequiel", "26", "Ezk"], ["Daniel", "Daniel", "daniel", "27", "Dan"], ["Hosea", "Oseas", "oseas", "28", "Hos"], ["Joel", "Joel", "joel", "29", "Joe"], ["Amos", "Amós", "amos", "30", "Amo"], ["Obadiah", "Abdías", "abdias", "31", "Oba"], ["Jonah", "Jonás", "jonas", "32", "Jon"], ["Micah", "Miqueas", "miqueas", "33", "Mic"], ["Nahum", "Nahúm", "nahum", "34", "Nam"], ["Habakkuk", "Habacuc", "habacuc", "35", "Hab"], ["Zephaniah", "Sofonías", "sofonias", "36", "Zep"], ["Haggai", "Hageo", "hageo", "37", "Hag"], ["Zechariah", "Zacarías", "zacarias", "38", "Zec"], ["Malachi", "Malaquías", "malaquias", "39", "Mal"]
];
export const BOOKS = rows.map(([name, spanish_name, translation_slug, number, macula_code]) => ({ name, spanish_name, translation_slug, number, macula_code }));
export function findBook(value) {
  const needle = String(value || "").trim().toLocaleLowerCase();
  return BOOKS.find(book => [book.name, book.spanish_name, book.translation_slug, `${book.number}-${book.macula_code}`].some(candidate => candidate.toLocaleLowerCase() === needle));
}
export function findBookByNumber(number) { return BOOKS.find(book => book.number === String(number).padStart(2, "0")); }
