#!/usr/bin/env python3
"""Seed Spanish→OSHB reverse-links for Zacarías. Biblia-LBF only.

Hand-only. Unwalked phrases get empty units (status=unwalked).
Never auto-zip. Never gloss DP.

Chapter 1 (phrases 0–20, Protestant 1:1–21): hand-mapped.
Chapter 2 (phrases 21–33, Protestant 2:1–13): hand-mapped.
Chapter 3 (phrases 34–43, Protestant 3:1–10): hand-mapped.
Chapter 4 (phrases 44–57, Protestant 4:1–14): hand-mapped.
Chapter 5 (phrases 58–68, Protestant 5:1–11): hand-mapped.
Chapter 6 (phrases 69–83, Protestant 6:1–15): hand-mapped.
Chapter 7 (phrases 84–97, Protestant 7:1–14): hand-mapped.
Chapter 8 (phrases 98–120, Protestant 8:1–23): hand-mapped.
Chapter 9 (phrases 121–137, Protestant 9:1–17): hand-mapped.
Chapter 10 (phrases 138–149, Protestant 10:1–12): hand-mapped.
Chapter 11 (phrases 150–166, Protestant 11:1–17): hand-mapped.
Chapter 12 (phrases 167–180, Protestant 12:1–14): hand-mapped.
Chapter 13 (phrases 181–189, Protestant 13:1–9): hand-mapped.
Chapter 14 (phrases 190–210, Protestant 14:1–21): hand-mapped.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path("/Users/johnwry/Nextcloud/Documents/GitHub/Biblia-LBF")
PHRASES = ROOT / "alignment/ot/zacarias/zacarias-phrases.json"
OUT = ROOT / "alignment/ot/zacarias/zacarias-reverse-links.json"

# phraseIndex → list of (spanish surface to find, tokenRows 0-based indexes)
# Surfaces are found left-to-right. Source indexes may be non-sequential.
HAND: dict[int, list[tuple[str, list[int]]]] = {
    0: [
        ("En el mes", [0]),
        ("octavo", [1]),
        ("en el año", [2]),
        ("segundo", [3]),
        ("de Darío", [4]),
        ("vino", [5]),
        ("palabra", [6]),
        ("de Jehová", [7]),
        ("a", [8]),
        ("Zacarías", [9]),
        ("hijo", [10]),
        ("de Berequías", [11]),
        ("hijo", [12]),
        ("de Iddo", [13]),
        ("el profeta", [14]),
        ("diciendo", [15]),
    ],
    1: [
        ("Se airó", [0]),
        ("Jehová", [1]),
        ("contra", [2]),
        ("sus padres", [3]),
        ("con ira", [4]),
    ],
    2: [
        ("Y les dirás", [0, 1]),
        ("Así", [2]),
        ("dice", [3]),
        ("Jehová", [4]),
        ("de los ejércitos", [5]),
        ("Vuélvanse", [6]),
        ("a mí", [7]),
        ("declara", [8]),
        ("Jehová", [9]),
        ("de los ejércitos", [10]),
        ("y yo me volveré", [11]),
        ("a ustedes", [12]),
        ("dice", [13]),
        ("Jehová", [14]),
        ("de los ejércitos", [15]),
    ],
    3: [
        ("No", [0]),
        ("sean", [1]),
        ("como sus padres", [2]),
        ("a quienes", [3]),
        ("los primeros", [7]),
        ("profetas", [6]),
        ("proclamaron", [4, 5]),
        ("diciendo", [8]),
        ("Así", [9]),
        ("dice", [10]),
        ("Jehová", [11]),
        ("de los ejércitos", [12]),
        ("Vuélvanse", [13]),
        ("ahora", [14]),
        ("de sus malos caminos", [15, 16]),
        ("y de sus malas obras", [17, 18]),
        ("Y no", [19]),
        ("oyeron", [20]),
        ("ni", [21]),
        ("prestaron atención", [22]),
        ("a mí", [23]),
        ("declara", [24]),
        ("Jehová", [25]),
    ],
    4: [
        ("Sus padres", [0]),
        ("dónde", [1]),
        ("están", [2]),
        ("Y los profetas", [3]),
        ("para siempre", [4]),
        ("vivirán", [5]),
    ],
    5: [
        ("Pero", [0]),
        ("mis palabras", [1]),
        ("y mis estatutos", [2]),
        ("que", [3]),
        ("mandé", [4]),
        ("a mis siervos", [5, 6]),
        ("los profetas", [7]),
        ("no", [8]),
        ("alcanzaron", [9]),
        ("a sus padres", [10]),
        ("Y se volvieron", [11]),
        ("y dijeron", [12]),
        ("Como", [13]),
        ("Jehová", [15]),
        ("de los ejércitos", [16]),
        ("se propuso", [14]),
        ("hacer", [17]),
        ("con nosotros", [18]),
        ("conforme a nuestros caminos", [19]),
        ("y conforme a nuestras obras", [20]),
        ("así", [21]),
        ("hizo", [22]),
        ("con nosotros", [23]),
    ],
    6: [
        ("En el día", [0]),
        ("veinticuatro", [1, 2]),
        ("del mes undécimo", [3, 4, 5]),
        ("que es", [6]),
        ("el mes", [7]),
        ("de Sebat", [8]),
        ("en el año", [9]),
        ("segundo", [10]),
        ("de Darío", [11]),
        ("vino", [12]),
        ("palabra", [13]),
        ("de Jehová", [14]),
        ("a", [15]),
        ("Zacarías", [16]),
        ("hijo", [17]),
        ("de Berequías", [18]),
        ("hijo", [19]),
        ("de Iddo", [20]),
        ("el profeta", [21]),
        ("diciendo", [22]),
    ],
    7: [
        ("Vi", [0]),
        ("de noche", [1]),
        ("y he aquí", [2]),
        ("un hombre", [3]),
        ("cabalgando", [4]),
        ("sobre", [5]),
        ("un caballo", [6]),
        ("rojo", [7]),
        ("y él", [8]),
        ("estaba de pie", [9]),
        ("entre", [10]),
        ("los mirtos", [11]),
        ("que", [12]),
        ("había en la hondonada", [13]),
        ("y detrás de él", [14]),
        ("caballos", [15]),
        ("rojos", [16]),
        ("alazanes", [17]),
        ("y blancos", [18]),
    ],
    8: [
        ("Y dije", [0]),
        ("Qué", [1]),
        ("son estos", [2]),
        ("señor mío", [3]),
        ("Y me dijo", [4, 5]),
        ("el ángel", [6]),
        ("que hablaba", [7]),
        ("conmigo", [8]),
        ("Yo", [9]),
        ("te mostraré", [10]),
        ("qué", [11]),
        ("son", [12]),
        ("estos", [13]),
    ],
    9: [
        ("Y respondió", [0]),
        ("el hombre", [1]),
        ("que estaba de pie", [2]),
        ("entre", [3]),
        ("los mirtos", [4]),
        ("y dijo", [5]),
        ("Estos", [6]),
        ("son los que", [7]),
        ("Jehová", [9]),
        ("envió", [8]),
        ("a recorrer", [10]),
        ("la tierra", [11]),
    ],
    10: [
        ("Y respondieron", [0]),
        ("al ángel", [1, 2]),
        ("de Jehová", [3]),
        ("que estaba de pie", [4]),
        ("entre", [5]),
        ("los mirtos", [6]),
        ("y dijeron", [7]),
        ("Hemos recorrido", [8]),
        ("la tierra", [9]),
        ("y he aquí", [10]),
        ("toda", [11]),
        ("la tierra", [12]),
        ("está asentada", [13]),
        ("y quieta", [14]),
    ],
    11: [
        ("Y respondió", [0]),
        ("el ángel", [1]),
        ("de Jehová", [2]),
        ("y dijo", [3]),
        ("Jehová", [4]),
        ("de los ejércitos", [5]),
        ("hasta", [6]),
        ("cuándo", [7]),
        ("tú", [8]),
        ("no", [9]),
        ("tendrás compasión", [10]),
        ("de Jerusalén", [11, 12]),
        ("y de las ciudades", [13, 14]),
        ("de Judá", [15]),
        ("contra las cuales", [16]),
        ("te has indignado", [17]),
        ("estos", [18]),
        ("setenta", [19]),
        ("años", [20]),
    ],
    12: [
        ("Y respondió", [0]),
        ("Jehová", [1]),
        ("al ángel", [2, 3]),
        ("que hablaba", [4]),
        ("conmigo", [5]),
        ("palabras", [6]),
        ("buenas", [7]),
        ("palabras", [8]),
        ("de consuelo", [9]),
    ],
    13: [
        ("Y me dijo", [0, 1]),
        ("el ángel", [2]),
        ("que hablaba", [3]),
        ("conmigo", [4]),
        ("Proclama", [5]),
        ("diciendo", [6]),
        ("Así", [7]),
        ("dice", [8]),
        ("Jehová", [9]),
        ("de los ejércitos", [10]),
        ("Celé", [11]),
        ("por Jerusalén", [12]),
        ("y por Sión", [13]),
        ("con gran celo", [14, 15]),
    ],
    14: [
        ("Y con gran ira", [0, 1]),
        ("estoy yo airado", [2, 3]),
        ("contra", [4]),
        ("las naciones", [5]),
        ("que están tranquilas", [6]),
        ("las cuales", [7]),
        ("yo", [8]),
        ("airé", [9]),
        ("un poco", [10]),
        ("y ellas", [11]),
        ("ayudaron", [12]),
        ("para mal", [13]),
    ],
    15: [
        ("Por tanto", [0]),
        ("así", [1]),
        ("dice", [2]),
        ("Jehová", [3]),
        ("Me he vuelto", [4]),
        ("a Jerusalén", [5]),
        ("con compasiones", [6]),
        ("mi casa", [7]),
        ("será edificada", [8]),
        ("en ella", [9]),
        ("declara", [10]),
        ("Jehová", [11]),
        ("de los ejércitos", [12]),
        ("y el cordel", [13]),
        ("será tendido", [14]),
        ("sobre", [15]),
        ("Jerusalén", [16]),
    ],
    16: [
        ("Proclama", [1]),
        ("otra vez", [0]),
        ("diciendo", [2]),
        ("Así", [3]),
        ("dice", [4]),
        ("Jehová", [5]),
        ("de los ejércitos", [6]),
        ("Aún", [7]),
        ("rebosarán", [8]),
        ("mis ciudades", [9]),
        ("de bien", [10]),
        ("y aún consolará", [11, 13]),
        ("Jehová", [12]),
        ("a Sión", [14, 15]),
        ("y aún escogerá", [16, 17]),
        ("a Jerusalén", [18]),
    ],
    17: [
        ("Y alcé", [0]),
        ("mis ojos", [1, 2]),
        ("y vi", [3]),
        ("y he aquí", [4]),
        ("cuatro", [5]),
        ("cuernos", [6]),
    ],
    18: [
        ("Y dije", [0]),
        ("al ángel", [1, 2]),
        ("que hablaba", [3]),
        ("conmigo", [4]),
        ("Qué", [5]),
        ("son estos", [6]),
        ("Y me dijo", [7, 8]),
        ("Estos", [9]),
        ("son los cuernos", [10]),
        ("que", [11]),
        ("dispersaron", [12]),
        ("a Judá", [13, 14]),
        ("a Israel", [15, 16]),
        ("y a Jerusalén", [17]),
    ],
    19: [
        ("Y me mostró", [0]),
        ("Jehová", [1]),
        ("cuatro", [2]),
        ("artesanos", [3]),
    ],
    20: [
        ("Y dije", [0]),
        ("Qué", [1]),
        ("vienen", [3]),
        ("estos", [2]),
        ("a hacer", [4]),
        ("Y dijo", [5]),
        ("diciendo", [6]),
        ("Estos", [7]),
        ("son los cuernos", [8]),
        ("que", [9]),
        ("dispersaron", [10]),
        ("a Judá", [11, 12]),
        ("de modo que", [13]),
        ("nadie", [14, 15]),
        ("alzó", [16]),
        ("su cabeza", [17]),
        ("y vinieron", [18]),
        ("estos", [19]),
        ("para aterrarlos", [20, 21]),
        ("para derribar", [22]),
        ("los cuernos", [23, 24]),
        ("de las naciones", [25]),
        ("que alzan", [26]),
        ("cuerno", [27]),
        ("contra", [28]),
        ("la tierra", [29]),
        ("de Judá", [30]),
        ("para dispersarla", [31]),
    ],
    21: [
        ("Y alcé", [0]),
        ("mis ojos", [1]),
        ("y vi", [2]),
        ("y he aquí", [3]),
        ("un hombre", [4]),
        ("y en su mano", [5]),
        ("un cordel", [6]),
        ("de medir", [7]),
    ],
    22: [
        ("Y dije", [0]),
        ("Adónde", [1]),
        ("vas", [3]),
        ("tú", [2]),
        ("Y me dijo", [4, 5]),
        ("A medir", [6]),
        ("a Jerusalén", [7, 8]),
        ("para ver", [9]),
        ("cuánta", [10]),
        ("es su anchura", [11]),
        ("y cuánta", [12]),
        ("su longitud", [13]),
    ],
    23: [
        ("Y he aquí", [0]),
        ("el ángel", [1]),
        ("que hablaba", [2]),
        ("conmigo", [3]),
        ("salía", [4]),
        ("y otro ángel", [5, 6]),
        ("salía", [7]),
        ("a su encuentro", [8]),
    ],
    24: [
        ("Y le dijo", [0, 1]),
        ("Corre", [2]),
        ("habla", [3]),
        ("a", [4]),
        ("aquel", [6]),
        ("joven", [5]),
        ("diciendo", [7]),
        ("Como lugares abiertos", [8]),
        ("será habitada", [9]),
        ("Jerusalén", [10]),
        ("por la multitud", [11]),
        ("de hombres", [12]),
        ("y de ganado", [13]),
        ("en medio de ella", [14]),
    ],
    25: [
        ("Y yo", [0]),
        ("seré", [1]),
        ("para ella", [2]),
        ("declara", [3]),
        ("Jehová", [4]),
        ("muro", [5]),
        ("de fuego", [6]),
        ("en derredor", [7]),
        ("y para gloria", [8]),
        ("seré", [9]),
        ("en medio de ella", [10]),
    ],
    26: [
        ("Ay", [0]),
        ("ay", [1]),
        ("Huyan", [2]),
        ("de la tierra", [3]),
        ("del norte", [4]),
        ("declara", [5]),
        ("Jehová", [6]),
        ("porque", [7]),
        ("como los cuatro", [8]),
        ("vientos", [9]),
        ("de los cielos", [10]),
        ("esparcí", [11]),
        ("a ustedes", [12]),
        ("declara", [13]),
        ("Jehová", [14]),
    ],
    27: [
        ("Ay", [0]),
        ("Sión", [1]),
        ("Escapa", [2]),
        ("tú que habitas", [3]),
        ("hija", [4]),
        ("de Babilonia", [5]),
    ],
    28: [
        ("Porque", [0]),
        ("así", [1]),
        ("dice", [2]),
        ("Jehová", [3]),
        ("de los ejércitos", [4]),
        ("Tras", [5]),
        ("la gloria", [6]),
        ("me envió", [7]),
        ("a", [8]),
        ("las naciones", [9]),
        ("que despojan", [10]),
        ("a ustedes", [11]),
        ("porque", [12]),
        ("el que toca", [13]),
        ("a ustedes", [14]),
        ("toca", [15]),
        ("la niña", [16]),
        ("de su ojo", [17]),
    ],
    29: [
        ("Porque", [0]),
        ("he aquí yo", [1]),
        ("agito", [2]),
        ("mi mano", [3, 4]),
        ("sobre ellas", [5]),
        ("y serán", [6]),
        ("despojo", [7]),
        ("para sus siervos", [8]),
        ("y sabrán", [9]),
        ("que", [10]),
        ("Jehová", [11]),
        ("de los ejércitos", [12]),
        ("me envió", [13]),
    ],
    30: [
        ("Canta de júbilo", [0]),
        ("y alégrate", [1]),
        ("hija", [2]),
        ("de Sión", [3]),
        ("porque", [4]),
        ("he aquí yo", [5]),
        ("vengo", [6]),
        ("y habitaré", [7]),
        ("en medio de ti", [8]),
        ("declara", [9]),
        ("Jehová", [10]),
    ],
    31: [
        ("Y se unirán", [0]),
        ("muchas", [2]),
        ("naciones", [1]),
        ("a", [3]),
        ("Jehová", [4]),
        ("en aquel día", [5, 6]),
        ("y serán", [7]),
        ("para mí", [8]),
        ("por pueblo", [9]),
        ("y habitaré", [10]),
        ("en medio de ti", [11]),
        ("y sabrás", [12]),
        ("que", [13]),
        ("Jehová", [14]),
        ("de los ejércitos", [15]),
        ("me envió", [16]),
        ("a ti", [17]),
    ],
    32: [
        ("Y heredará", [0]),
        ("Jehová", [1]),
        ("a Judá", [2, 3]),
        ("su porción", [4]),
        ("sobre", [5]),
        ("la tierra", [6]),
        ("santa", [7]),
        ("y escogerá", [8]),
        ("aún", [9]),
        ("a Jerusalén", [10]),
    ],
    33: [
        ("Silencio", [0]),
        ("toda", [1]),
        ("carne", [2]),
        ("delante de", [3]),
        ("Jehová", [4]),
        ("porque", [5]),
        ("él se ha despertado", [6]),
        ("de la morada", [7]),
        ("de su santidad", [8]),
    ],
    34: [
        ("Y me mostró", [0]),
        ("a Josué", [1, 2]),
        ("el sumo sacerdote", [3, 4]),
        ("de pie", [5]),
        ("delante", [6]),
        ("del ángel", [7]),
        ("de Jehová", [8]),
        ("y el acusador", [9]),
        ("estaba de pie", [10]),
        ("a", [11]),
        ("su derecha", [12]),
        ("para acusarlo", [13]),
    ],
    35: [
        ("Y dijo", [0]),
        ("Jehová", [1]),
        ("al acusador", [2, 3]),
        ("Jehová", [5]),
        ("te", [6]),
        ("reprenda", [4]),
        ("acusador", [7]),
        ("y te reprenda", [8, 10]),
        ("Jehová", [9]),
        ("el que escoge", [11]),
        ("a Jerusalén", [12]),
        ("No", [13]),
        ("es este", [14]),
        ("un tizón", [15]),
        ("arrebatado", [16]),
        ("del fuego", [17]),
    ],
    36: [
        ("Y Josué", [0]),
        ("estaba", [1]),
        ("vestido", [2]),
        ("de ropas", [3]),
        ("inmundas", [4]),
        ("y de pie", [5]),
        ("delante", [6]),
        ("del ángel", [7]),
    ],
    37: [
        ("Y respondió", [0]),
        ("y dijo", [1]),
        ("a", [2]),
        ("los que estaban de pie", [3]),
        ("delante de él", [4]),
        ("diciendo", [5]),
        ("Quiten", [6]),
        ("de sobre él", [9]),
        ("las ropas", [7]),
        ("inmundas", [8]),
        ("Y le dijo", [10, 11]),
        ("Mira", [12]),
        ("he hecho pasar", [13]),
        ("de sobre ti", [14]),
        ("tu iniquidad", [15]),
        ("y te vestiré", [16, 17]),
        ("de ropas de gala", [18]),
    ],
    38: [
        ("Y dije", [0]),
        ("Pongan", [1]),
        ("un turbante", [2]),
        ("puro", [3]),
        ("sobre", [4]),
        ("su cabeza", [5]),
        ("Y pusieron", [6]),
        ("el turbante", [7]),
        ("puro", [8]),
        ("sobre", [9]),
        ("su cabeza", [10]),
        ("y lo vistieron", [11]),
        ("de ropas", [12]),
        ("y el ángel", [13]),
        ("de Jehová", [14]),
        ("estaba de pie", [15]),
    ],
    39: [
        ("Y el ángel de Jehová amonestó", [0, 1, 2]),
        ("a Josué", [3]),
        ("diciendo", [4]),
    ],
    40: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("Si", [4]),
        ("andas", [6]),
        ("en mis caminos", [5]),
        ("y si", [7]),
        ("guardas", [10]),
        ("mi encargo", [8, 9]),
        ("entonces tú también", [11, 12]),
        ("juzgarás", [13]),
        ("mi casa", [14, 15]),
        ("y también", [16]),
        ("guardarás", [17]),
        ("mis atrios", [18, 19]),
        ("y te daré", [20, 21]),
        ("paso", [22]),
        ("entre", [23]),
        ("estos", [25]),
        ("que están de pie", [24]),
    ],
    41: [
        ("Oye", [0]),
        ("ahora", [1]),
        ("Josué", [2]),
        ("el sumo sacerdote", [3, 4]),
        ("tú", [5]),
        ("y tus compañeros", [6]),
        ("que están sentados", [7]),
        ("delante de ti", [8]),
        ("porque", [9]),
        ("ellos son", [12]),
        ("hombres", [10]),
        ("de señal", [11]),
        ("porque", [13]),
        ("he aquí yo", [14]),
        ("traigo", [15]),
        ("a mi siervo", [16, 17]),
        ("Renuevo", [18]),
    ],
    42: [
        ("Porque", [0]),
        ("he aquí", [1]),
        ("la piedra", [2]),
        ("que", [3]),
        ("he puesto", [4]),
        ("delante de", [5]),
        ("Josué", [6]),
        ("sobre", [7]),
        ("una", [9]),
        ("piedra", [8]),
        ("siete", [10]),
        ("ojos", [11]),
        ("He aquí yo", [12]),
        ("grabo", [13]),
        ("su grabadura", [14]),
        ("declara", [15]),
        ("Jehová", [16]),
        ("de los ejércitos", [17]),
        ("y quitaré", [18]),
        ("la iniquidad", [19, 20]),
        ("de aquella tierra", [21, 22]),
        ("en un día", [23, 24]),
    ],
    43: [
        ("En aquel día", [0, 1]),
        ("declara", [2]),
        ("Jehová", [3]),
        ("de los ejércitos", [4]),
        ("llamarán", [5]),
        ("cada uno", [6]),
        ("a su prójimo", [7]),
        ("debajo de la vid", [8, 9, 10]),
        ("y debajo de la higuera", [11, 12, 13]),
    ],
    44: [
        ("Y volvió", [0]),
        ("el ángel", [1]),
        ("que hablaba", [2]),
        ("conmigo", [3]),
        ("y me despertó", [4]),
        ("como un hombre", [5]),
        ("que", [6]),
        ("es despertado", [7]),
        ("de su sueño", [8]),
    ],
    45: [
        ("Y me dijo", [0, 1]),
        ("Qué", [2]),
        ("ves", [4]),
        ("tú", [3]),
        ("Y dijo", [5]),
        ("He visto", [6]),
        ("y he aquí", [7]),
        ("un candelabro", [8]),
        ("de oro", [9]),
        ("todo él", [10]),
        ("y su tazón", [11]),
        ("sobre", [12]),
        ("su cabeza", [13]),
        ("y sus siete lámparas", [14, 15]),
        ("sobre él", [16]),
        ("siete", [17]),
        ("y siete", [18]),
        ("tubos", [19]),
        ("para las lámparas", [20]),
        ("que", [21]),
        ("están sobre", [22]),
        ("su cabeza", [23]),
    ],
    46: [
        ("Y dos", [0]),
        ("olivos", [1]),
        ("sobre él", [2]),
        ("uno", [3]),
        ("a la derecha", [4]),
        ("del tazón", [5]),
        ("y otro", [6]),
        ("sobre", [7]),
        ("su izquierda", [8]),
    ],
    47: [
        ("Y respondí", [0]),
        ("y dije", [1]),
        ("al ángel", [2, 3]),
        ("que hablaba", [4]),
        ("conmigo", [5]),
        ("diciendo", [6]),
        ("Qué", [7]),
        ("son estos", [8]),
        ("señor mío", [9]),
    ],
    48: [
        ("Y respondió", [0]),
        ("el ángel", [1]),
        ("que hablaba", [2]),
        ("conmigo", [3]),
        ("y me dijo", [4, 5]),
        ("No", [6]),
        ("sabes", [7]),
        ("qué", [8]),
        ("son", [9]),
        ("estos", [10]),
        ("Y dije", [11]),
        ("No", [12]),
        ("señor mío", [13]),
    ],
    49: [
        ("Y respondió", [0]),
        ("y me dijo", [1, 2]),
        ("diciendo", [3]),
        ("Esta", [4]),
        ("es palabra", [5]),
        ("de Jehová", [6]),
        ("a", [7]),
        ("Zorobabel", [8]),
        ("diciendo", [9]),
        ("No", [10]),
        ("con ejército", [11]),
        ("ni", [12]),
        ("con fuerza", [13]),
        ("sino", [14, 15]),
        ("con mi Espíritu", [16]),
        ("dice", [17]),
        ("Jehová", [18]),
        ("de los ejércitos", [19]),
    ],
    50: [
        ("Quién", [0]),
        ("eres tú", [1]),
        ("el gran monte", [2, 3]),
        ("Delante de", [4]),
        ("Zorobabel", [5]),
        ("a llanura", [6]),
        ("Y sacará", [7]),
        ("la piedra", [8, 9]),
        ("principal", [10]),
        ("aclamaciones", [11]),
        ("Gracia", [12]),
        ("gracia", [13]),
        ("a ella", [14]),
    ],
    51: [
        ("Y vino", [0]),
        ("palabra", [1]),
        ("de Jehová", [2]),
        ("a mí", [3]),
        ("diciendo", [4]),
    ],
    52: [
        ("Las manos", [0]),
        ("de Zorobabel", [1]),
        ("pusieron el cimiento", [2]),
        ("de esta casa", [3, 4]),
        ("y sus manos", [5]),
        ("la acabarán", [6]),
        ("y sabrás", [7]),
        ("que", [8]),
        ("Jehová", [9]),
        ("de los ejércitos", [10]),
        ("me envió", [11]),
        ("a ustedes", [12]),
    ],
    53: [
        ("Porque", [0]),
        ("quién", [1]),
        ("menospreció", [2]),
        ("el día", [3]),
        ("de las pequeñeces", [4]),
        ("Y se alegrarán", [5]),
        ("y verán", [6]),
        ("la piedra", [7, 8]),
        ("de estaño", [9]),
        ("en la mano", [10]),
        ("de Zorobabel", [11]),
        ("Estos", [13]),
        ("siete", [12]),
        ("los ojos", [14]),
        ("de Jehová", [15]),
        ("ellos", [16]),
        ("recorren", [17]),
        ("toda", [18]),
        ("la tierra", [19]),
    ],
    54: [
        ("Y respondí", [0]),
        ("y le dije", [1, 2]),
        ("Qué", [3]),
        ("son estos", [6]),
        ("dos", [4]),
        ("olivos", [5]),
        ("a la derecha", [7, 8]),
        ("del candelabro", [9]),
        ("y a su izquierda", [10, 11]),
    ],
    55: [
        ("Y respondí", [0]),
        ("por segunda vez", [1]),
        ("y le dije", [2, 3]),
        ("Qué", [4]),
        ("son las dos", [5]),
        ("ramas", [6]),
        ("de los olivos", [7]),
        ("que", [8]),
        ("están en la mano", [9]),
        ("de los dos", [10]),
        ("tubos", [11]),
        ("de oro", [12]),
        ("que vierten", [13]),
        ("de sobre ellos", [14]),
        ("el oro", [15]),
    ],
    56: [
        ("Y me dijo", [0, 1]),
        ("diciendo", [2]),
        ("No", [3]),
        ("sabes", [4]),
        ("qué", [5]),
        ("son estos", [6]),
        ("Y dije", [7]),
        ("No", [8]),
        ("señor mío", [9]),
    ],
    57: [
        ("Y dijo", [0]),
        ("Estos", [1]),
        ("son los dos", [2]),
        ("hijos", [3]),
        ("del aceite", [4]),
        ("que están de pie", [5]),
        ("junto al Señor", [6, 7]),
        ("de toda", [8]),
        ("la tierra", [9]),
    ],
    58: [
        ("Y volví", [0]),
        ("y alcé", [1]),
        ("mis ojos", [2]),
        ("y vi", [3]),
        ("y he aquí", [4]),
        ("un rollo", [5]),
        ("que volaba", [6]),
    ],
    59: [
        ("Y me dijo", [0, 1]),
        ("Qué", [2]),
        ("ves", [4]),
        ("tú", [3]),
        ("Y dije", [5]),
        ("Yo", [6]),
        ("veo", [7]),
        ("un rollo", [8]),
        ("que vuela", [9]),
        ("su longitud", [10]),
        ("es de veinte codos", [11, 12]),
        ("y su anchura", [13]),
        ("de diez codos", [14, 15]),
    ],
    60: [
        ("Y me dijo", [0, 1]),
        ("Esta", [2]),
        ("es la maldición", [3]),
        ("que sale", [4]),
        ("sobre", [5]),
        ("la faz", [6]),
        ("de toda", [7]),
        ("la tierra", [8]),
        ("porque", [9]),
        ("todo", [10]),
        ("el que hurta", [11]),
        ("de este", [12]),
        ("conforme a ella", [13]),
        ("es limpiado", [14]),
        ("y todo", [15]),
        ("el que jura", [16]),
        ("de este", [17]),
        ("conforme a ella", [18]),
        ("es limpiado", [19]),
    ],
    61: [
        ("La he sacado", [0]),
        ("declara", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("y vendrá", [4]),
        ("a", [5]),
        ("la casa", [6]),
        ("del ladrón", [7]),
        ("y a", [8]),
        ("la casa", [9]),
        ("del que jura", [10]),
        ("en mi nombre", [11]),
        ("para mentira", [12]),
        ("y morará", [13]),
        ("en medio", [14]),
        ("de su casa", [15]),
        ("y la consumirá", [16]),
        ("y", [17]),
        ("sus maderos", [18]),
        ("y", [19]),
        ("sus piedras", [20]),
    ],
    62: [
        ("Y salió", [0]),
        ("el ángel", [1]),
        ("que hablaba", [2]),
        ("conmigo", [3]),
        ("y me dijo", [4, 5]),
        ("Alza", [6]),
        ("ahora", [7]),
        ("tus ojos", [8]),
        ("y mira", [9]),
        ("qué", [10]),
        ("es esta", [12]),
        ("que sale", [11]),
    ],
    63: [
        ("Y dije", [0]),
        ("Qué", [1]),
        ("es", [2]),
        ("Y dijo", [3]),
        ("Esta", [4]),
        ("es la efa", [5]),
        ("que sale", [6]),
        ("Y dijo", [7]),
        ("Esta", [8]),
        ("es el ojo de ellos", [9]),
        ("en toda", [10]),
        ("la tierra", [11]),
    ],
    64: [
        ("Y he aquí", [0]),
        ("un talento", [1]),
        ("de plomo", [2]),
        ("levantado", [3]),
        ("y esta", [4]),
        ("una", [6]),
        ("mujer", [5]),
        ("sentada", [7]),
        ("en medio", [8]),
        ("de la efa", [9]),
    ],
    65: [
        ("Y dijo", [0]),
        ("Esta", [1]),
        ("es la maldad", [2]),
        ("Y la arrojó", [3, 4]),
        ("al medio", [5, 6]),
        ("de la efa", [7]),
        ("y arrojó", [8]),
        ("la piedra", [9, 10]),
        ("de plomo", [11]),
        ("a", [12]),
        ("la boca de ella", [13]),
    ],
    66: [
        ("Y alcé", [0]),
        ("mis ojos", [1]),
        ("y vi", [2]),
        ("y he aquí", [3]),
        ("dos", [4]),
        ("mujeres", [5]),
        ("que salían", [6]),
        ("y viento", [7]),
        ("en sus alas", [8]),
        ("y a ellas", [9]),
        ("alas", [10]),
        ("como las alas", [11]),
        ("de la cigüeña", [12]),
        ("Y levantaron", [13]),
        ("la efa", [14, 15]),
        ("entre", [16]),
        ("la tierra", [17]),
        ("y", [18]),
        ("los cielos", [19]),
    ],
    67: [
        ("Y dije", [0]),
        ("al ángel", [1, 2]),
        ("que hablaba", [3]),
        ("conmigo", [4]),
        ("Adónde", [5]),
        ("llevan", [6, 7]),
        ("la efa", [8, 9]),
    ],
    68: [
        ("Y me dijo", [0, 1]),
        ("Para edificarle", [2, 3]),
        ("una casa", [4]),
        ("en la tierra", [5]),
        ("de Sinar", [6]),
        ("y será preparado", [7]),
        ("y será asentada", [8]),
        ("allí", [9]),
        ("sobre", [10]),
        ("su base", [11]),
    ],
    69: [
        ("Y volví", [0]),
        ("y alcé", [1]),
        ("mis ojos", [2]),
        ("y vi", [3]),
        ("y he aquí", [4]),
        ("cuatro", [5]),
        ("carros", [6]),
        ("que salían", [7]),
        ("de entre", [8]),
        ("los dos", [9]),
        ("montes", [10]),
        ("y los montes", [11]),
        ("eran montes", [12]),
        ("de bronce", [13]),
    ],
    70: [
        ("En el primer carro", [0, 1]),
        ("caballos", [2]),
        ("rojos", [3]),
        ("y en el segundo carro", [4, 5]),
        ("caballos", [6]),
        ("negros", [7]),
    ],
    71: [
        ("Y en el tercer carro", [0, 1]),
        ("caballos", [2]),
        ("blancos", [3]),
        ("y en el cuarto carro", [4, 5]),
        ("caballos", [6]),
        ("manchados", [7]),
        ("fuertes", [8]),
    ],
    72: [
        ("Y respondí", [0]),
        ("y dije", [1]),
        ("al ángel", [2, 3]),
        ("que hablaba", [4]),
        ("conmigo", [5]),
        ("Qué", [6]),
        ("son estos", [7]),
        ("señor mío", [8]),
    ],
    73: [
        ("Y respondió", [0]),
        ("el ángel", [1]),
        ("y me dijo", [2, 3]),
        ("Estos", [4]),
        ("son los cuatro", [5]),
        ("vientos", [6]),
        ("de los cielos", [7]),
        ("que salen", [8]),
        ("de presentarse", [9]),
        ("junto al Señor", [10, 11]),
        ("de toda", [12]),
        ("la tierra", [13]),
    ],
    74: [
        ("Los caballos", [2]),
        ("negros", [3]),
        ("que están en ella", [0, 1]),
        ("salen", [4]),
        ("hacia", [5]),
        ("la tierra", [6]),
        ("del norte", [7]),
        ("y los blancos", [8]),
        ("salieron", [9]),
        ("tras ellos", [10, 11]),
        ("y los manchados", [12]),
        ("salieron", [13]),
        ("hacia", [14]),
        ("la tierra", [15]),
        ("del sur", [16]),
    ],
    75: [
        ("Y los fuertes", [0]),
        ("salieron", [1]),
        ("y procuraron", [2]),
        ("ir", [3]),
        ("a recorrer", [4]),
        ("la tierra", [5]),
        ("Y dijo", [6]),
        ("Vayan", [7]),
        ("recorran", [8]),
        ("la tierra", [9]),
        ("Y recorrieron", [10]),
        ("la tierra", [11]),
    ],
    76: [
        ("Y me gritó", [0, 1]),
        ("y me habló", [2, 3]),
        ("diciendo", [4]),
        ("Mira", [5]),
        ("los que salen", [6]),
        ("hacia", [7]),
        ("la tierra", [8]),
        ("del norte", [9]),
        ("han hecho reposar", [10]),
        ("mi espíritu", [11, 12]),
        ("en la tierra", [13]),
        ("del norte", [14]),
    ],
    77: [
        ("Y vino", [0]),
        ("palabra", [1]),
        ("de Jehová", [2]),
        ("a mí", [3]),
        ("diciendo", [4]),
    ],
    78: [
        ("Toma", [0]),
        ("de los desterrados", [1, 2]),
        ("de Heldai", [3]),
        ("y de", [4]),
        ("Tobías", [5]),
        ("y de", [6]),
        ("Jedaías", [7]),
        ("y ven", [8]),
        ("tú", [9]),
        ("en aquel día", [10, 11]),
        ("y entra", [12]),
        ("en casa", [13]),
        ("de Josías", [14]),
        ("hijo", [15]),
        ("de Sofonías", [16]),
        ("que", [17]),
        ("vinieron", [18]),
        ("de Babilonia", [19]),
    ],
    79: [
        ("Y tomarás", [0]),
        ("plata", [1]),
        ("y oro", [2]),
        ("y harás", [3]),
        ("coronas", [4]),
        ("y las pondrás", [5]),
        ("en la cabeza", [6]),
        ("de Josué", [7]),
        ("hijo", [8]),
        ("de Josadac", [9]),
        ("el sumo sacerdote", [10, 11]),
    ],
    80: [
        ("Y le hablarás", [0, 1]),
        ("diciendo", [2]),
        ("Así", [3]),
        ("dice", [4]),
        ("Jehová", [5]),
        ("de los ejércitos", [6]),
        ("diciendo", [7]),
        ("He aquí", [8]),
        ("el hombre", [9]),
        ("Renuevo", [10]),
        ("es su nombre", [11]),
        ("y de debajo de él", [12]),
        ("brotará", [13]),
        ("y edificará", [14]),
        ("el templo", [15, 16]),
        ("de Jehová", [17]),
    ],
    81: [
        ("Y él", [0]),
        ("edificará", [1]),
        ("el templo", [2, 3]),
        ("de Jehová", [4]),
        ("y él", [5]),
        ("llevará", [6]),
        ("la majestad", [7]),
        ("y se sentará", [8]),
        ("y gobernará", [9]),
        ("sobre", [10]),
        ("su trono", [11]),
        ("y será", [12]),
        ("sacerdote", [13]),
        ("sobre", [14]),
        ("su trono", [15]),
        ("y consejo", [16]),
        ("de paz", [17]),
        ("habrá", [18]),
        ("entre", [19]),
        ("ambos", [20]),
    ],
    82: [
        ("Y las coronas", [0]),
        ("serán", [1]),
        ("para Helem", [2]),
        ("y para Tobías", [3]),
        ("y para Jedaías", [4]),
        ("y para Hen", [5]),
        ("hijo", [6]),
        ("de Sofonías", [7]),
        ("como memorial", [8]),
        ("en el templo", [9]),
        ("de Jehová", [10]),
    ],
    83: [
        ("Y los que están lejos", [0]),
        ("vendrán", [1]),
        ("y edificarán", [2]),
        ("en el templo", [3]),
        ("de Jehová", [4]),
        ("y sabrán", [5]),
        ("que", [6]),
        ("Jehová", [7]),
        ("de los ejércitos", [8]),
        ("me envió", [9]),
        ("a ustedes", [10]),
        ("Y será", [11]),
        ("si", [12]),
        ("de oír", [13]),
        ("oyen", [14]),
        ("la voz", [15]),
        ("de Jehová", [16]),
        ("su Dios", [17]),
    ],
    84: [
        ("Y aconteció", [0]),
        ("en el año", [1]),
        ("cuarto", [2]),
        ("de Darío", [3]),
        ("el rey", [4]),
        ("vino", [5]),
        ("palabra", [6]),
        ("de Jehová", [7]),
        ("a", [8]),
        ("Zacarías", [9]),
        ("en el cuatro", [10]),
        ("del mes", [11]),
        ("noveno", [12]),
        ("en Quisleu", [13]),
    ],
    85: [
        ("Y envió", [0]),
        ("Bet-el", [1, 2]),
        ("a Sarezer", [3, 4]),
        ("y a Regem-melec", [5, 6]),
        ("y a sus hombres", [7]),
        ("para implorar", [8]),
        ("el rostro", [9, 10]),
        ("de Jehová", [11]),
    ],
    86: [
        ("diciendo", [0]),
        ("a", [1]),
        ("los sacerdotes", [2]),
        ("que", [3]),
        ("son de la casa", [4]),
        ("de Jehová", [5]),
        ("de los ejércitos", [6]),
        ("y a", [7]),
        ("los profetas", [8]),
        ("diciendo", [9]),
        ("Lloraré", [10]),
        ("en el mes", [11]),
        ("quinto", [12]),
        ("absteniéndome", [13]),
        ("como", [14]),
        ("he hecho", [15]),
        ("esto", [16]),
        ("cuántos", [17]),
        ("años", [18]),
    ],
    87: [
        ("Y vino", [0]),
        ("palabra", [1]),
        ("de Jehová", [2]),
        ("de los ejércitos", [3]),
        ("a mí", [4]),
        ("diciendo", [5]),
    ],
    88: [
        ("Di", [0]),
        ("a", [1]),
        ("todo", [2]),
        ("el pueblo", [3]),
        ("de la tierra", [4]),
        ("y a", [5]),
        ("los sacerdotes", [6]),
        ("diciendo", [7]),
        ("Cuando", [8]),
        ("ayunaron", [9]),
        ("y lamentando", [10]),
        ("en el quinto", [11]),
        ("y en el séptimo", [12]),
        ("y esto", [13]),
        ("setenta", [14]),
        ("años", [15]),
        ("de ayunar", [16]),
        ("me ayunaron a mí", [17]),
        ("yo", [18]),
    ],
    89: [
        ("Y cuando", [0]),
        ("comen", [1]),
        ("y cuando", [2]),
        ("beben", [3]),
        ("no", [4]),
        ("son ustedes", [5]),
        ("los que comen", [6]),
        ("y ustedes", [7]),
        ("los que beben", [8]),
    ],
    90: [
        ("No", [0]),
        ("son las palabras", [1, 2]),
        ("que", [3]),
        ("proclamó", [4]),
        ("Jehová", [5]),
        ("por mano", [6]),
        ("de los primeros", [8]),
        ("profetas", [7]),
        ("cuando", [9]),
        ("Jerusalén", [10]),
        ("estaba habitada", [11]),
        ("y tranquila", [12]),
        ("y sus ciudades", [13]),
        ("alrededor de ella", [14]),
        ("y el Neguev", [15]),
        ("y la Sefela", [16]),
        ("habitaba", [17]),
    ],
    91: [
        ("Y vino", [0]),
        ("palabra", [1]),
        ("de Jehová", [2]),
        ("a", [3]),
        ("Zacarías", [4]),
        ("diciendo", [5]),
    ],
    92: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("diciendo", [4]),
        ("Juzguen", [7]),
        ("juicio", [5]),
        ("verdadero", [6]),
        ("y hagan", [10]),
        ("misericordia", [8]),
        ("y compasiones", [9]),
        ("cada uno", [11]),
        ("con", [12]),
        ("su hermano", [13]),
    ],
    93: [
        ("Y a la viuda", [0]),
        ("y al huérfano", [1]),
        ("al extranjero", [2]),
        ("y al pobre", [3]),
        ("no", [4]),
        ("opriman", [5]),
        ("y el mal", [6]),
        ("de un hombre", [7]),
        ("su hermano", [8]),
        ("no", [9]),
        ("piensen", [10]),
        ("en su corazón", [11]),
    ],
    94: [
        ("Y rehusaron", [0]),
        ("prestar atención", [1]),
        ("y dieron", [2]),
        ("hombro", [3]),
        ("rebelde", [4]),
        ("y sus oídos", [5]),
        ("hicieron pesados", [6]),
        ("para no oír", [7]),
    ],
    95: [
        ("Y su corazón", [0]),
        ("pusieron", [1]),
        ("como diamante", [2]),
        ("para no oír", [3]),
        ("la ley", [4, 5]),
        ("y", [6]),
        ("las palabras", [7]),
        ("que", [8]),
        ("envió", [9]),
        ("Jehová", [10]),
        ("de los ejércitos", [11]),
        ("por su Espíritu", [12]),
        ("por mano", [13]),
        ("de los primeros", [15]),
        ("profetas", [14]),
        ("y hubo", [16]),
        ("gran", [18]),
        ("ira", [17]),
        ("de parte de", [19]),
        ("Jehová", [20]),
        ("de los ejércitos", [21]),
    ],
    96: [
        ("Y aconteció", [0]),
        ("como", [1]),
        ("él llamó", [2]),
        ("y no", [3]),
        ("oyeron", [4]),
        ("así", [5]),
        ("ellos llamarán", [6]),
        ("y yo no", [7]),
        ("oiré", [8]),
        ("dijo", [9]),
        ("Jehová", [10]),
        ("de los ejércitos", [11]),
    ],
    97: [
        ("Y los lanzaré con torbellino", [0]),
        ("sobre", [1]),
        ("todas", [2]),
        ("las naciones", [3]),
        ("que", [4]),
        ("no", [5]),
        ("los conocieron", [6]),
        ("y la tierra", [7]),
        ("fue asolada", [8]),
        ("tras ellos", [9]),
        ("sin quien pasa", [10]),
        ("y sin quien vuelve", [11]),
        ("y pusieron", [12]),
        ("una tierra", [13]),
        ("deseable", [14]),
        ("en desolación", [15]),
    ],
    98: [
        ("Y vino", [0]),
        ("palabra", [1]),
        ("de Jehová", [2]),
        ("de los ejércitos", [3]),
        ("diciendo", [4]),
    ],
    99: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("Celé", [4]),
        ("por Sión", [5]),
        ("con gran celo", [6, 7]),
        ("y con gran furor", [8, 9]),
        ("celé", [10]),
        ("por ella", [11]),
    ],
    100: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("Me he vuelto", [3]),
        ("a Sión", [4, 5]),
        ("y habitaré", [6]),
        ("en medio", [7]),
        ("de Jerusalén", [8]),
        ("y Jerusalén será llamada", [9, 10]),
        ("Ciudad", [11]),
        ("de la Verdad", [12]),
        ("y el monte", [13]),
        ("de Jehová", [14]),
        ("de los ejércitos", [15]),
        ("monte", [16]),
        ("de la santidad", [17]),
    ],
    101: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("Aún", [4]),
        ("se sentarán", [5]),
        ("ancianos", [6]),
        ("y ancianas", [7]),
        ("en las plazas", [8]),
        ("de Jerusalén", [9]),
        ("y un hombre", [10]),
        ("su bastón", [11]),
        ("en su mano", [12]),
        ("por la multitud", [13]),
        ("de días", [14]),
    ],
    102: [
        ("Y las plazas", [0]),
        ("de la ciudad", [1]),
        ("se llenarán", [2]),
        ("de niños", [3]),
        ("y niñas", [4]),
        ("jugando", [5]),
        ("en sus plazas", [6]),
    ],
    103: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("Si", [4]),
        ("es maravilloso", [5]),
        ("a los ojos", [6]),
        ("del remanente", [7]),
        ("de este pueblo", [8, 9]),
        ("en aquellos días", [10, 11]),
        ("también", [12]),
        ("a mis ojos", [13]),
        ("será maravilloso", [14]),
        ("declara", [15]),
        ("Jehová", [16]),
        ("de los ejércitos", [17]),
    ],
    104: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("He aquí yo", [4]),
        ("salvo", [5]),
        ("a mi pueblo", [6, 7]),
        ("de la tierra", [8]),
        ("del oriente", [9]),
        ("y de la tierra", [10]),
        ("de la entrada", [11]),
        ("del sol", [12]),
    ],
    105: [
        ("Y los traeré", [0, 1]),
        ("y habitarán", [2]),
        ("en medio", [3]),
        ("de Jerusalén", [4]),
        ("y serán", [5]),
        ("para mí", [6]),
        ("por pueblo", [7]),
        ("y yo", [8]),
        ("seré", [9]),
        ("para ellos", [10]),
        ("por Dios", [11]),
        ("en verdad", [12]),
        ("y en justicia", [13]),
    ],
    106: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("Sean fuertes", [4]),
        ("sus manos", [5]),
        ("los que oyen", [6]),
        ("en estos días", [7, 8]),
        ("estas palabras", [9, 10, 11]),
        ("de la boca", [12]),
        ("de los profetas", [13]),
        ("que", [14]),
        ("en el día", [15]),
        ("en que fue cimentada", [16]),
        ("la casa", [17]),
        ("de Jehová", [18]),
        ("de los ejércitos", [19]),
        ("el templo", [20]),
        ("para ser edificado", [21]),
    ],
    107: [
        ("Porque", [0]),
        ("antes de", [1]),
        ("aquellos días", [2, 3]),
        ("no hubo", [6, 7]),
        ("paga", [4]),
        ("para el hombre", [5]),
        ("ni paga para la bestia", [8, 9, 10]),
        ("ni para el que salía", [11]),
        ("ni para el que entraba", [12]),
        ("había paz", [13, 14]),
        ("a causa del", [15]),
        ("adversario", [16]),
        ("y yo solté", [17]),
        ("a todo hombre", [18, 19, 20]),
        ("cada uno", [21]),
        ("contra su prójimo", [22]),
    ],
    108: [
        ("Y ahora", [0]),
        ("no", [1]),
        ("como los días", [2]),
        ("primeros", [3]),
        ("soy yo", [4]),
        ("para el remanente", [5]),
        ("de este pueblo", [6, 7]),
        ("declara", [8]),
        ("Jehová", [9]),
        ("de los ejércitos", [10]),
    ],
    109: [
        ("Porque", [0]),
        ("siembra", [1]),
        ("de paz", [2]),
        ("la vid", [3]),
        ("dará", [4]),
        ("su fruto", [5]),
        ("y la tierra", [6]),
        ("dará", [7]),
        ("su producto", [8, 9]),
        ("y los cielos", [10]),
        ("darán", [11]),
        ("su rocío", [12]),
        ("y haré heredar", [13]),
        ("al remanente", [14, 15]),
        ("de este pueblo", [16, 17]),
        ("todas estas cosas", [18, 19, 20]),
    ],
    110: [
        ("Y será que", [0]),
        ("como", [1]),
        ("fueron", [2]),
        ("maldición", [3]),
        ("entre las naciones", [4]),
        ("casa", [5]),
        ("de Judá", [6]),
        ("y casa", [7]),
        ("de Israel", [8]),
        ("así", [9]),
        ("los salvaré", [10, 11]),
        ("y serán", [12]),
        ("bendición", [13]),
        ("No", [14]),
        ("teman", [15]),
        ("sean fuertes", [16]),
        ("sus manos", [17]),
    ],
    111: [
        ("Porque", [0]),
        ("así", [1]),
        ("dice", [2]),
        ("Jehová", [3]),
        ("de los ejércitos", [4]),
        ("Como", [5]),
        ("me propuse", [6]),
        ("hacerles mal", [7, 8]),
        ("cuando sus padres me provocaron a ira", [9, 10, 11]),
        ("dice", [12]),
        ("Jehová", [13]),
        ("de los ejércitos", [14]),
        ("y no", [15]),
        ("me arrepentí", [16]),
    ],
    112: [
        ("así", [0]),
        ("me he vuelto", [1]),
        ("me he propuesto", [2]),
        ("en estos días", [3, 4]),
        ("hacer bien", [5]),
        ("a Jerusalén", [6, 7]),
        ("y a", [8]),
        ("la casa", [9]),
        ("de Judá", [10]),
        ("No", [11]),
        ("teman", [12]),
    ],
    113: [
        ("Estas", [0]),
        ("son las cosas", [1]),
        ("que", [2]),
        ("harán", [3]),
        ("Hablen", [4]),
        ("verdad", [5]),
        ("cada uno", [6]),
        ("con", [7]),
        ("su prójimo", [8]),
        ("verdad", [9]),
        ("y juicio", [10]),
        ("de paz", [11]),
        ("juzguen", [12]),
        ("en sus puertas", [13]),
    ],
    114: [
        ("Y el mal de su prójimo", [0, 1, 2, 3]),
        ("no", [4]),
        ("piensen", [5]),
        ("en su corazón", [6]),
        ("ni", [9]),
        ("amen", [10]),
        ("juramento", [7]),
        ("de mentira", [8]),
        ("porque", [11]),
        ("todas estas", [12, 13, 14]),
        ("que", [15]),
        ("aborrecí", [16]),
        ("declara", [17]),
        ("Jehová", [18]),
    ],
    115: [
        ("Y vino", [0]),
        ("palabra", [1]),
        ("de Jehová", [2]),
        ("de los ejércitos", [3]),
        ("a mí", [4]),
        ("diciendo", [5]),
    ],
    116: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("El ayuno", [4]),
        ("del cuarto", [5]),
        ("y el ayuno", [6]),
        ("del quinto", [7]),
        ("y el ayuno", [8]),
        ("del séptimo", [9]),
        ("y el ayuno", [10]),
        ("del décimo", [11]),
        ("será", [12]),
        ("para la casa", [13]),
        ("de Judá", [14]),
        ("para gozo", [15]),
        ("y para alegría", [16]),
        ("y para fiestas", [17]),
        ("buenas", [18]),
        ("Amen", [21]),
        ("la verdad", [19]),
        ("y la paz", [20]),
    ],
    117: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("Aún", [4]),
        ("vendrán", [5, 6]),
        ("pueblos", [7]),
        ("y habitantes", [8]),
        ("de muchas ciudades", [9, 10]),
    ],
    118: [
        ("Y irán", [0]),
        ("los habitantes", [1]),
        ("de una", [2]),
        ("a", [3]),
        ("otra", [4]),
        ("diciendo", [5]),
        ("Vamos", [6]),
        ("de ir", [7]),
        ("a implorar", [8]),
        ("el rostro", [9, 10]),
        ("de Jehová", [11]),
        ("y a buscar", [12]),
        ("a Jehová", [13, 14]),
        ("de los ejércitos", [15]),
        ("Iré", [16]),
        ("también", [17]),
        ("yo", [18]),
    ],
    119: [
        ("Y vendrán", [0]),
        ("muchos", [2]),
        ("pueblos", [1]),
        ("y naciones", [3]),
        ("poderosas", [4]),
        ("a buscar", [5]),
        ("a Jehová", [6, 7]),
        ("de los ejércitos", [8]),
        ("en Jerusalén", [9]),
        ("y a implorar", [10]),
        ("el rostro", [11, 12]),
        ("de Jehová", [13]),
    ],
    120: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("de los ejércitos", [3]),
        ("En aquellos días", [4, 5]),
        ("asirán", [6, 7]),
        ("diez", [8]),
        ("hombres", [9]),
        ("de todas", [10]),
        ("las lenguas", [11]),
        ("de las naciones", [12]),
        ("y asirán", [13]),
        ("la orla", [14]),
        ("de un hombre", [15]),
        ("judío", [16]),
        ("diciendo", [17]),
        ("Iremos", [18]),
        ("con ustedes", [19]),
        ("porque", [20]),
        ("hemos oído", [21]),
        ("que Dios", [22]),
        ("está con ustedes", [23]),
    ],
    121: [
        ("Carga", [0]),
        ("de la palabra", [1]),
        ("de Jehová", [2]),
        ("en la tierra", [3]),
        ("de Hadrac", [4]),
        ("y Damasco", [5]),
        ("su reposo", [6]),
        ("porque", [7]),
        ("de Jehová es", [8]),
        ("el ojo", [9]),
        ("del hombre", [10]),
        ("y todas", [11]),
        ("las tribus", [12]),
        ("de Israel", [13]),
    ],
    122: [
        ("Y también", [0]),
        ("Hamat", [1]),
        ("confina", [2]),
        ("con ella", [3]),
        ("Tiro", [4]),
        ("y Sidón", [5]),
        ("porque", [6]),
        ("es muy sabia", [7, 8]),
    ],
    123: [
        ("Y Tiro se edificó", [0, 1, 3]),
        ("fortaleza", [2]),
        ("y amontonó", [4]),
        ("plata", [5]),
        ("como polvo", [6]),
        ("y oro fino", [7]),
        ("como lodo", [8]),
        ("de las calles", [9]),
    ],
    124: [
        ("He aquí", [0]),
        ("el Señor", [1]),
        ("la desposeerá", [2]),
        ("y herirá", [3]),
        ("en el mar", [4]),
        ("su poderío", [5]),
        ("y ella", [6]),
        ("en el fuego", [7]),
        ("será consumida", [8]),
    ],
    125: [
        ("Verá", [0]),
        ("Ascalón", [1]),
        ("y temerá", [2]),
        ("y Gaza", [3]),
        ("y se retorcerá", [4]),
        ("mucho", [5]),
        ("y Ecrón", [6]),
        ("porque", [7]),
        ("su esperanza", [9]),
        ("ha sido avergonzada", [8]),
        ("Y perecerá", [10]),
        ("el rey", [11]),
        ("de Gaza", [12]),
        ("y Ascalón", [13]),
        ("no", [14]),
        ("será habitada", [15]),
    ],
    126: [
        ("Y habitará", [0]),
        ("un bastardo", [1]),
        ("en Asdod", [2]),
        ("y cortaré", [3]),
        ("la soberbia", [4]),
        ("de los filisteos", [5]),
    ],
    127: [
        ("Y quitaré", [0]),
        ("su sangre", [1]),
        ("de su boca", [2]),
        ("y sus abominaciones", [3]),
        ("de entre", [4]),
        ("sus dientes", [5]),
        ("y quedará", [6]),
        ("también", [7]),
        ("él", [8]),
        ("para nuestro Dios", [9]),
        ("y será", [10]),
        ("como un jefe", [11]),
        ("en Judá", [12]),
        ("y Ecrón", [13]),
        ("como el jebuseo", [14]),
    ],
    128: [
        ("Y acamparé", [0]),
        ("por mi casa", [1]),
        ("una guarnición", [2]),
        ("de quien pasa", [3]),
        ("y de quien vuelve", [4]),
        ("y no", [5]),
        ("pasará", [6]),
        ("más", [8]),
        ("sobre ellos", [7]),
        ("un opresor", [9]),
        ("porque", [10]),
        ("ahora", [11]),
        ("he visto", [12]),
        ("con mis ojos", [13]),
    ],
    129: [
        ("Alégrate", [0]),
        ("mucho", [1]),
        ("hija", [2]),
        ("de Sión", [3]),
        ("da voces", [4]),
        ("hija", [5]),
        ("de Jerusalén", [6]),
        ("He aquí", [7]),
        ("tu rey", [8]),
        ("vendrá", [9]),
        ("a ti", [10]),
        ("justo", [11]),
        ("y salvo", [12]),
        ("es él", [13]),
        ("pobre", [14]),
        ("y cabalgando", [15]),
        ("sobre", [16]),
        ("un asno", [17]),
        ("y sobre", [18]),
        ("un pollino", [19]),
        ("hijo", [20]),
        ("de asnas", [21]),
    ],
    130: [
        ("Y cortaré", [0]),
        ("el carro", [1]),
        ("de Efraín", [2]),
        ("y el caballo", [3]),
        ("de Jerusalén", [4]),
        ("y será cortado", [5]),
        ("el arco", [6]),
        ("de guerra", [7]),
        ("y hablará", [8]),
        ("paz", [9]),
        ("a las naciones", [10]),
        ("y su señorío será", [11]),
        ("de mar", [12]),
        ("a mar", [13, 14]),
        ("y desde el río", [15]),
        ("hasta", [16]),
        ("los confines", [17]),
        ("de la tierra", [18]),
    ],
    131: [
        ("También", [0]),
        ("tú", [1]),
        ("por la sangre", [2]),
        ("de tu pacto", [3]),
        ("he soltado", [4]),
        ("a tus presos", [5]),
        ("del pozo", [6]),
        ("no hay", [7]),
        ("agua", [8]),
        ("en él", [9]),
    ],
    132: [
        ("Vuélvanse", [0]),
        ("a la fortaleza", [1]),
        ("presos", [2]),
        ("de la esperanza", [3]),
        ("también", [4]),
        ("hoy", [5]),
        ("anuncio", [6]),
        ("el doble", [7]),
        ("te devolveré", [8, 9]),
    ],
    133: [
        ("Porque", [0]),
        ("he tensado", [1]),
        ("para mí", [2]),
        ("a Judá", [3]),
        ("arco", [4]),
        ("llené", [5]),
        ("a Efraín", [6]),
        ("y despertaré", [7]),
        ("a tus hijos", [8]),
        ("Sión", [9]),
        ("contra", [10]),
        ("tus hijos", [11]),
        ("Grecia", [12]),
        ("y te pondré", [13]),
        ("como espada", [14]),
        ("de valiente", [15]),
    ],
    134: [
        ("Y Jehová", [0]),
        ("será visto", [2]),
        ("sobre ellos", [1]),
        ("y su saeta", [5]),
        ("saldrá", [3]),
        ("como el relámpago", [4]),
        ("y el Señor", [6]),
        ("Jehová", [7]),
        ("tocará", [9]),
        ("el cuerno", [8]),
        ("e irá", [10]),
        ("con torbellinos", [11]),
        ("del sur", [12]),
    ],
    135: [
        ("Jehová", [0]),
        ("de los ejércitos", [1]),
        ("los protegerá", [2, 3]),
        ("y devorarán", [4]),
        ("y someterán", [5]),
        ("las piedras", [6]),
        ("de honda", [7]),
        ("y beberán", [8]),
        ("harán estruendo", [9]),
        ("como", [10]),
        ("vino", [11]),
        ("y se llenarán", [12]),
        ("como el tazón", [13]),
        ("como las esquinas", [14]),
        ("del altar", [15]),
    ],
    136: [
        ("Y los salvará", [0]),
        ("Jehová", [1]),
        ("su Dios", [2]),
        ("en aquel día", [3, 4]),
        ("como rebaño", [5]),
        ("de su pueblo", [6]),
        ("porque", [7]),
        ("piedras", [8]),
        ("de diadema", [9]),
        ("ondeando", [10]),
        ("sobre", [11]),
        ("su tierra", [12]),
    ],
    137: [
        ("Porque", [0]),
        ("qué", [1]),
        ("su bondad", [2]),
        ("y qué", [3]),
        ("su hermosura", [4]),
        ("El trigo", [5]),
        ("a los jóvenes", [6]),
        ("y el mosto", [7]),
        ("hará fructificar", [8]),
        ("a las doncellas", [9]),
    ],
    138: [
        ("Pidan", [0]),
        ("de Jehová", [1]),
        ("lluvia", [2]),
        ("en tiempo", [3]),
        ("de lluvia tardía", [4]),
        ("Jehová", [5]),
        ("hace", [6]),
        ("relámpagos", [7]),
        ("y lluvia", [8]),
        ("de aguacero", [9]),
        ("dará", [10]),
        ("a ellos", [11]),
        ("a un hombre", [12]),
        ("hierba", [13]),
        ("en el campo", [14]),
    ],
    139: [
        ("Porque", [0]),
        ("los terafines", [1]),
        ("hablaron", [2]),
        ("iniquidad", [3]),
        ("y los adivinos", [4]),
        ("vieron", [5]),
        ("mentira", [6]),
        ("y sueños", [7]),
        ("de la vanidad", [8]),
        ("hablan", [9]),
        ("vanidad", [10]),
        ("consuelan", [11]),
        ("por eso", [12, 13]),
        ("partieron", [14]),
        ("como", [15]),
        ("rebaño", [16]),
        ("son afligidos", [17]),
        ("porque", [18]),
        ("no hay", [19]),
        ("pastor", [20]),
    ],
    140: [
        ("Sobre", [0]),
        ("los pastores", [1]),
        ("se encendió", [2]),
        ("mi ira", [3]),
        ("y sobre", [4]),
        ("los machos cabríos", [5]),
        ("visitaré", [6]),
        ("porque", [7]),
        ("visitó", [8]),
        ("Jehová", [9]),
        ("de los ejércitos", [10]),
        ("su rebaño", [11, 12]),
        ("la casa", [13, 14]),
        ("de Judá", [15]),
        ("y los puso", [16, 17]),
        ("como caballo", [18]),
        ("de su esplendor", [19]),
        ("en la batalla", [20]),
    ],
    141: [
        ("De él", [0]),
        ("la esquina", [1]),
        ("de él", [2]),
        ("la estaca", [3]),
        ("de él", [4]),
        ("el arco", [5]),
        ("de guerra", [6]),
        ("de él", [7]),
        ("saldrá", [8]),
        ("todo", [9]),
        ("opresor", [10]),
        ("juntamente", [11]),
    ],
    142: [
        ("Y serán", [0]),
        ("como valientes", [1]),
        ("pisando", [2]),
        ("en el lodo", [3]),
        ("de las calles", [4]),
        ("en la batalla", [5]),
        ("y pelearán", [6]),
        ("porque", [7]),
        ("Jehová", [8]),
        ("está con ellos", [9]),
        ("y secarán", [10]),
        ("a los que cabalgan", [11]),
        ("caballos", [12]),
    ],
    143: [
        ("Y fortaleceré", [0]),
        ("la casa", [1, 2]),
        ("de Judá", [3]),
        ("y la casa", [4, 5]),
        ("de José", [6]),
        ("salvaré", [7]),
        ("y los haré volver", [8]),
        ("porque", [9]),
        ("me apiadé de ellos", [10]),
        ("y serán", [11]),
        ("como que", [12]),
        ("no", [13]),
        ("los deseché", [14]),
        ("porque", [15]),
        ("yo soy", [16]),
        ("Jehová", [17]),
        ("su Dios", [18]),
        ("y les responderé", [19]),
    ],
    144: [
        ("Y serán", [0]),
        ("como valiente", [1]),
        ("Efraín", [2]),
        ("y se alegrará", [3]),
        ("su corazón", [4]),
        ("como", [5]),
        ("vino", [6]),
        ("y sus hijos", [7]),
        ("verán", [8]),
        ("y se alegrarán", [9]),
        ("se gozará", [10]),
        ("su corazón", [11]),
        ("en Jehová", [12]),
    ],
    145: [
        ("Silbaré", [0]),
        ("a ellos", [1]),
        ("y los reuniré", [2]),
        ("porque", [3]),
        ("los redimí", [4]),
        ("y se multiplicarán", [5]),
        ("como", [6]),
        ("se multiplicaron", [7]),
    ],
    146: [
        ("Y los sembraré", [0]),
        ("en los pueblos", [1]),
        ("y en las lejanías", [2]),
        ("se acordarán de mí", [3]),
        ("y vivirán", [4]),
        ("con", [5]),
        ("sus hijos", [6]),
        ("y volverán", [7]),
    ],
    147: [
        ("Y los haré volver", [0]),
        ("de la tierra", [1]),
        ("de Egipto", [2]),
        ("y de Asiria", [3]),
        ("los reuniré", [4]),
        ("y a", [5]),
        ("la tierra", [6]),
        ("de Galaad", [7]),
        ("y al Líbano", [8]),
        ("los traeré", [9]),
        ("y no", [10]),
        ("será hallado", [11]),
        ("para ellos", [12]),
    ],
    148: [
        ("Y pasará", [0]),
        ("en el mar", [1]),
        ("angustia", [2]),
        ("y herirá", [3]),
        ("en el mar", [4]),
        ("olas", [5]),
        ("y secarán", [6]),
        ("todas", [7]),
        ("las profundidades", [8]),
        ("del Nilo", [9]),
        ("y será abatida", [10]),
        ("la soberbia", [11]),
        ("de Asiria", [12]),
        ("y el cetro", [13]),
        ("de Egipto", [14]),
        ("se apartará", [15]),
    ],
    149: [
        ("Y los fortaleceré", [0]),
        ("en Jehová", [1]),
        ("y en su nombre", [2]),
        ("andarán", [3]),
        ("declara", [4]),
        ("Jehová", [5]),
    ],
    150: [
        ("Abre", [0]),
        ("Líbano", [1]),
        ("tus puertas", [2]),
        ("y coma", [3]),
        ("fuego", [4]),
        ("en tus cedros", [5]),
    ],
    151: [
        ("Aúlla", [0]),
        ("ciprés", [1]),
        ("porque", [2]),
        ("cayó", [3]),
        ("cedro", [4]),
        ("que", [5]),
        ("magníficos", [6]),
        ("fueron devastados", [7]),
        ("Aúllen", [8]),
        ("encinas", [9]),
        ("de Basán", [10]),
        ("porque", [11]),
        ("bajó", [12]),
        ("el bosque", [13]),
        ("fortificado", [14]),
    ],
    152: [
        ("Voz", [0]),
        ("de aullido", [1]),
        ("de los pastores", [2]),
        ("porque", [3]),
        ("fue devastado", [4]),
        ("su manto", [5]),
        ("voz", [6]),
        ("de rugido", [7]),
        ("de leoncillos", [8]),
        ("porque", [9]),
        ("fue devastada", [10]),
        ("la soberbia", [11]),
        ("del Jordán", [12]),
    ],
    153: [
        ("Así", [0]),
        ("dice", [1]),
        ("Jehová", [2]),
        ("mi Dios", [3]),
        ("Apacienta", [4]),
        ("el rebaño", [5, 6]),
        ("de la matanza", [7]),
    ],
    154: [
        ("Cuyos", [0]),
        ("compradores", [1]),
        ("las matarán", [2]),
        ("y no", [3]),
        ("serán culpables", [4]),
        ("y sus vendedores", [5]),
        ("dirá", [6]),
        ("Bendito", [7]),
        ("Jehová", [8]),
        ("y me enriqueceré", [9]),
        ("y sus pastores", [10]),
        ("no", [11]),
        ("se apiadará", [12]),
        ("sobre ellas", [13]),
    ],
    155: [
        ("Porque", [0]),
        ("no", [1]),
        ("me apiadaré", [2]),
        ("más", [3]),
        ("de los habitantes", [4, 5]),
        ("de la tierra", [6]),
        ("declara", [7]),
        ("Jehová", [8]),
        ("y he aquí yo", [9, 10]),
        ("hago hallar", [11]),
        ("al hombre", [12, 13]),
        ("un hombre", [14]),
        ("en mano", [15]),
        ("de su prójimo", [16]),
        ("y en mano", [17]),
        ("de su rey", [18]),
        ("y aplastarán", [19]),
        ("la tierra", [20, 21]),
        ("y no", [22]),
        ("libraré", [23]),
        ("de su mano", [24]),
    ],
    156: [
        ("Y apacenté", [0]),
        ("el rebaño", [1, 2]),
        ("de la matanza", [3]),
        ("por tanto", [4]),
        ("los pobres", [5]),
        ("del rebaño", [6]),
        ("Y tomé", [7]),
        ("para mí", [8]),
        ("dos", [9]),
        ("cayados", [10]),
        ("al uno", [11]),
        ("llamé", [12]),
        ("Agrado", [13]),
        ("y al uno", [14]),
        ("llamé", [15]),
        ("Cuerdas", [16]),
        ("y apacenté", [17]),
        ("el rebaño", [18, 19]),
    ],
    157: [
        ("Y hice desaparecer", [0]),
        ("a los tres", [1, 2]),
        ("pastores", [3]),
        ("en un mes", [4, 5]),
        ("y se acortó", [6]),
        ("mi alma", [7]),
        ("en ellos", [8]),
        ("y también", [9]),
        ("el alma de ellos", [10]),
        ("aborreció", [11]),
        ("en mí", [12]),
    ],
    158: [
        ("Y dije", [0]),
        ("No", [1]),
        ("apacentaré", [2]),
        ("a ustedes", [3]),
        ("la que muere", [4]),
        ("morirá", [5]),
        ("y la que desaparece", [6]),
        ("desaparecerá", [7]),
        ("y las que quedan", [8]),
        ("comerán", [9]),
        ("cada una", [10]),
        ("la carne", [11, 12]),
        ("de su compañera", [13]),
    ],
    159: [
        ("Y tomé", [0]),
        ("mi cayado", [1, 2]),
        ("Agrado", [3, 4]),
        ("y lo corté", [5, 6]),
        ("para romper", [7]),
        ("mi pacto", [8, 9]),
        ("que", [10]),
        ("corté", [11]),
        ("con", [12]),
        ("todos", [13]),
        ("los pueblos", [14]),
    ],
    160: [
        ("Y fue rota", [0]),
        ("en aquel día", [1, 2]),
        ("y conocieron", [3]),
        ("así", [4]),
        ("los pobres", [5]),
        ("del rebaño", [6]),
        ("los que me guardan", [7, 8]),
        ("que", [9]),
        ("palabra", [10]),
        ("de Jehová", [11]),
        ("es él", [12]),
    ],
    161: [
        ("Y dije", [0]),
        ("a ellos", [1]),
        ("Si", [2]),
        ("es bueno", [3]),
        ("en los ojos de ustedes", [4]),
        ("den", [5]),
        ("mi salario", [6]),
        ("y si", [7]),
        ("no", [8]),
        ("cesen", [9]),
        ("Y pesaron", [10]),
        ("mi salario", [11, 12]),
        ("treinta", [13]),
        ("de plata", [14]),
    ],
    162: [
        ("Y dijo", [0]),
        ("Jehová", [1]),
        ("a mí", [2]),
        ("Arrójalo", [3]),
        ("al alfarero", [4, 5]),
        ("esplendor", [6]),
        ("del precio", [7]),
        ("que", [8]),
        ("fui estimado", [9]),
        ("de sobre ellos", [10]),
        ("Y tomé", [11]),
        ("treinta", [12]),
        ("la plata", [13]),
        ("y lo arrojé", [14, 15]),
        ("casa", [16]),
        ("de Jehová", [17]),
        ("al alfarero", [18, 19]),
    ],
    163: [
        ("Y corté", [0]),
        ("mi cayado", [1, 2]),
        ("el segundo", [3]),
        ("las Cuerdas", [4, 5]),
        ("para romper", [6]),
        ("la hermandad", [7, 8]),
        ("entre", [9]),
        ("Judá", [10]),
        ("y entre", [11]),
        ("Israel", [12]),
    ],
    164: [
        ("Y dijo", [0]),
        ("Jehová", [1]),
        ("a mí", [2]),
        ("Aún", [3]),
        ("toma", [4]),
        ("para ti", [5]),
        ("instrumento", [6]),
        ("de pastor", [7]),
        ("necio", [8]),
    ],
    165: [
        ("Porque", [0]),
        ("he aquí yo", [1, 2]),
        ("levanto", [3]),
        ("un pastor", [4]),
        ("en la tierra", [5]),
        ("las desaparecidas", [6]),
        ("no", [7]),
        ("visitará", [8]),
        ("el muchacho", [9]),
        ("no", [10]),
        ("buscará", [11]),
        ("y la quebrada", [12]),
        ("no", [13]),
        ("sanará", [14]),
        ("la que está en pie", [15]),
        ("no", [16]),
        ("sustentará", [17]),
        ("y la carne", [18]),
        ("de la gorda", [19]),
        ("comerá", [20]),
        ("y las pezuñas de ellas", [21]),
        ("despedazará", [22]),
    ],
    166: [
        ("Ay", [0]),
        ("pastor", [1]),
        ("de la nada", [2]),
        ("dejador", [3]),
        ("del rebaño", [4]),
        ("Espada", [5]),
        ("sobre", [6]),
        ("su brazo", [7]),
        ("y sobre", [8]),
        ("el ojo", [9]),
        ("de su derecha", [10]),
        ("su brazo", [11]),
        ("secándose", [12]),
        ("se secará", [13]),
        ("y el ojo", [14]),
        ("de su derecha", [15]),
        ("oscureciéndose", [16]),
        ("se oscurecerá", [17]),
    ],
    167: [
        ("Carga", [0]),
        ("de la palabra", [1]),
        ("de Jehová", [2]),
        ("sobre", [3]),
        ("Israel", [4]),
        ("Declara", [5]),
        ("Jehová", [6]),
        ("el que extiende", [7]),
        ("los cielos", [8]),
        ("y funda", [9]),
        ("la tierra", [10]),
        ("y forma", [11]),
        ("el espíritu", [12]),
        ("del hombre", [13]),
        ("en su interior", [14]),
    ],
    168: [
        ("He aquí yo", [0, 1]),
        ("pongo", [2]),
        ("a Jerusalén", [3, 4]),
        ("cuenco", [5]),
        ("de vértigo", [6]),
        ("para todos", [7]),
        ("los pueblos", [8]),
        ("en derredor", [9]),
        ("y también", [10]),
        ("sobre", [11]),
        ("Judá", [12]),
        ("será", [13]),
        ("en el asedio", [14]),
        ("sobre", [15]),
        ("Jerusalén", [16]),
    ],
    169: [
        ("Y será", [0]),
        ("en aquel día", [1, 2]),
        ("pondré", [3]),
        ("a Jerusalén", [4, 5]),
        ("piedra", [6]),
        ("de carga", [7]),
        ("para todos", [8]),
        ("los pueblos", [9]),
        ("todos", [10]),
        ("los que la cargan", [11]),
        ("rasguñando", [12]),
        ("serán rasguñados", [13]),
        ("y se reunirán", [14]),
        ("sobre ella", [15]),
        ("todas", [16]),
        ("las naciones", [17]),
        ("de la tierra", [18]),
    ],
    170: [
        ("En aquel día", [0, 1]),
        ("declara", [2]),
        ("Jehová", [3]),
        ("heriré", [4]),
        ("a todo", [5]),
        ("caballo", [6]),
        ("con el estupor", [7]),
        ("y a su jinete", [8]),
        ("con la locura", [9]),
        ("y sobre", [10]),
        ("la casa", [11]),
        ("de Judá", [12]),
        ("abriré", [13]),
        ("mis ojos", [14, 15]),
        ("y a todo", [16]),
        ("caballo", [17]),
        ("de los pueblos", [18]),
        ("heriré", [19]),
        ("con la ceguera", [20]),
    ],
    171: [
        ("Y dirán", [0]),
        ("los jefes", [1]),
        ("de Judá", [2]),
        ("en su corazón", [3]),
        ("Fortaleza", [4]),
        ("para mí", [5]),
        ("son los habitantes", [6]),
        ("de Jerusalén", [7]),
        ("en Jehová", [8]),
        ("de los ejércitos", [9]),
        ("su Dios", [10]),
    ],
    172: [
        ("En aquel día", [0, 1]),
        ("pondré", [2]),
        ("a los jefes", [3, 4]),
        ("de Judá", [5]),
        ("como brasero", [6]),
        ("de fuego", [7]),
        ("en leños", [8]),
        ("y como antorcha", [9]),
        ("de fuego", [10]),
        ("en gavilla", [11]),
        ("y comerán", [12]),
        ("sobre", [13]),
        ("la derecha", [14]),
        ("y sobre", [15]),
        ("la izquierda", [16]),
        ("a todos", [17, 18]),
        ("los pueblos", [19]),
        ("en derredor", [20]),
        ("y habitará", [21]),
        ("Jerusalén", [22]),
        ("aún", [23]),
        ("debajo de ella", [24]),
        ("en Jerusalén", [25]),
    ],
    173: [
        ("Y salvará", [0]),
        ("Jehová", [1]),
        ("las tiendas", [2, 3]),
        ("de Judá", [4]),
        ("primero", [5]),
        ("para que", [6]),
        ("no", [7]),
        ("se engrandeza", [8]),
        ("la hermosura", [9]),
        ("de la casa", [10]),
        ("de David", [11]),
        ("y la hermosura", [12]),
        ("del habitante", [13]),
        ("de Jerusalén", [14]),
        ("sobre", [15]),
        ("Judá", [16]),
    ],
    174: [
        ("En aquel día", [0, 1]),
        ("escudará", [2]),
        ("Jehová", [3]),
        ("en favor", [4]),
        ("del habitante", [5]),
        ("de Jerusalén", [6]),
        ("y será", [7]),
        ("el que tropieza", [8]),
        ("entre ellos", [9]),
        ("en aquel día", [10, 11]),
        ("como David", [12]),
        ("y la casa", [13]),
        ("de David", [14]),
        ("como Dios", [15]),
        ("como el ángel", [16]),
        ("de Jehová", [17]),
        ("delante de ellos", [18]),
    ],
    175: [
        ("Y será", [0]),
        ("en aquel día", [1, 2]),
        ("buscaré", [3]),
        ("destruir", [4]),
        ("a todas", [5, 6]),
        ("las naciones", [7]),
        ("que vienen", [8]),
        ("sobre", [9]),
        ("Jerusalén", [10]),
    ],
    176: [
        ("Y derramaré", [0]),
        ("sobre", [1]),
        ("la casa", [2]),
        ("de David", [3]),
        ("y sobre", [4]),
        ("el habitante", [5]),
        ("de Jerusalén", [6]),
        ("espíritu", [7]),
        ("de gracia", [8]),
        ("y de súplicas", [9]),
        ("y mirarán", [10]),
        ("a mí", [11]),
        ("a quien", [12, 13]),
        ("traspasaron", [14]),
        ("y lamentarán", [15]),
        ("sobre él", [16]),
        ("como lamento", [17]),
        ("sobre", [18]),
        ("el único", [19]),
        ("y amargándose", [20]),
        ("sobre él", [21]),
        ("como amargarse", [22]),
        ("sobre", [23]),
        ("el primogénito", [24]),
    ],
    177: [
        ("En aquel día", [0, 1]),
        ("será grande", [2]),
        ("el lamento", [3]),
        ("en Jerusalén", [4]),
        ("como el lamento", [5]),
        ("de Hadad-rimón", [6, 7]),
        ("en el valle", [8]),
        ("de Meguidón", [9]),
    ],
    178: [
        ("Y lamentará", [0]),
        ("la tierra", [1]),
        ("familias", [2]),
        ("familias", [3]),
        ("aparte", [4]),
        ("la familia", [5]),
        ("de la casa", [6]),
        ("de David", [7]),
        ("aparte", [8]),
        ("y sus mujeres", [9]),
        ("aparte", [10]),
        ("la familia", [11]),
        ("de la casa", [12]),
        ("de Natán", [13]),
        ("aparte", [14]),
        ("y sus mujeres", [15]),
        ("aparte", [16]),
    ],
    179: [
        ("La familia", [0]),
        ("de la casa", [1]),
        ("de Leví", [2]),
        ("aparte", [3]),
        ("y sus mujeres", [4]),
        ("aparte", [5]),
        ("la familia", [6]),
        ("del simeíta", [7]),
        ("aparte", [8]),
        ("y sus mujeres", [9]),
        ("aparte", [10]),
    ],
    180: [
        ("Todas", [0]),
        ("las familias", [1]),
        ("que quedan", [2]),
        ("familias", [3]),
        ("familias", [4]),
        ("aparte", [5]),
        ("y sus mujeres", [6]),
        ("aparte", [7]),
    ],
    181: [
        ("En aquel día", [0, 1]),
        ("habrá", [2]),
        ("un manantial", [3]),
        ("abierto", [4]),
        ("para la casa", [5]),
        ("de David", [6]),
        ("y para los habitantes", [7]),
        ("de Jerusalén", [8]),
        ("para pecado", [9]),
        ("y para impureza", [10]),
    ],
    182: [
        ("Y será", [0]),
        ("en aquel día", [1, 2]),
        ("declara", [3]),
        ("Jehová", [4]),
        ("de los ejércitos", [5]),
        ("cortaré", [6]),
        ("los nombres", [7, 8]),
        ("de los ídolos", [9]),
        ("de la tierra", [10, 11]),
        ("y no", [12]),
        ("serán recordados", [13]),
        ("más", [14]),
        ("y también", [15]),
        ("a los profetas", [16, 17]),
        ("y el espíritu", [18, 19]),
        ("de la inmundicia", [20]),
        ("haré pasar", [21]),
        ("de la tierra", [22, 23]),
    ],
    183: [
        ("Y será", [0]),
        ("cuando", [1]),
        ("profetice", [2]),
        ("un hombre", [3]),
        ("aún", [4]),
        ("y le dirán", [5, 6]),
        ("su padre", [7]),
        ("y su madre", [8]),
        ("sus engendradores", [9]),
        ("No", [10]),
        ("vivirás", [11]),
        ("porque", [12]),
        ("mentira", [13]),
        ("hablaste", [14]),
        ("en el nombre", [15]),
        ("de Jehová", [16]),
        ("y lo traspasarán", [17]),
        ("su padre", [18]),
        ("y su madre", [19]),
        ("sus engendradores", [20]),
        ("en su profetizar", [21]),
    ],
    184: [
        ("Y será", [0]),
        ("en aquel día", [1, 2]),
        ("se avergonzarán", [3]),
        ("los profetas", [4]),
        ("cada uno", [5]),
        ("de su visión", [6]),
        ("en su profetizar", [7]),
        ("y no", [8]),
        ("vestirán", [9]),
        ("manto", [10]),
        ("de pelo", [11]),
        ("para", [12]),
        ("mentir", [13]),
    ],
    185: [
        ("Y dirá", [0]),
        ("No", [1]),
        ("soy", [3]),
        ("profeta", [2]),
        ("hombre", [4]),
        ("que trabaja", [5]),
        ("la tierra", [6]),
        ("soy yo", [7]),
        ("porque", [8]),
        ("un hombre", [9]),
        ("me adquirió", [10]),
        ("desde mi juventud", [11]),
    ],
    186: [
        ("Y le dirá", [0, 1]),
        ("Qué son", [2]),
        ("estas", [4]),
        ("heridas", [3]),
        ("entre", [5]),
        ("tus manos", [6]),
        ("Y dirá", [7]),
        ("Que", [8]),
        ("fui herido", [9]),
        ("casa", [10]),
        ("de mis amadores", [11]),
    ],
    187: [
        ("Espada", [0]),
        ("despierta", [1]),
        ("sobre", [2]),
        ("mi pastor", [3]),
        ("y sobre", [4]),
        ("hombre", [5]),
        ("de mi compañero", [6]),
        ("declara", [7]),
        ("Jehová", [8]),
        ("de los ejércitos", [9]),
        ("Hiere", [10]),
        ("al pastor", [11, 12]),
        ("y se dispersarán", [13]),
        ("el rebaño", [14]),
        ("y volveré", [15]),
        ("mi mano", [16]),
        ("sobre", [17]),
        ("los pequeños", [18]),
    ],
    188: [
        ("Y será", [0]),
        ("en toda", [1]),
        ("la tierra", [2]),
        ("declara", [3]),
        ("Jehová", [4]),
        ("porción", [5]),
        ("de dos", [6]),
        ("en ella", [7]),
        ("serán cortados", [8]),
        ("expirarán", [9]),
        ("y la tercera", [10]),
        ("quedará", [11]),
        ("en ella", [12]),
    ],
    189: [
        ("Y traeré", [0]),
        ("la tercera", [1, 2]),
        ("en el fuego", [3]),
        ("y los refinaré", [4]),
        ("como refinar", [5]),
        ("la plata", [6, 7]),
        ("y los probaré", [8]),
        ("como probar", [9]),
        ("el oro", [10, 11]),
        ("Él", [12]),
        ("llamará", [13]),
        ("en mi nombre", [14]),
        ("y yo", [15]),
        ("responderé", [16]),
        ("a él", [17]),
        ("Dije", [18]),
        ("Pueblo mío", [19]),
        ("es él", [20]),
        ("y él", [21]),
        ("dirá", [22]),
        ("Jehová", [23]),
        ("mi Dios", [24]),
    ],
    190: [
        ("He aquí", [0]),
        ("día", [1]),
        ("viene", [2]),
        ("para Jehová", [3]),
        ("y será repartido", [4]),
        ("tu despojo", [5]),
        ("en tu interior", [6]),
    ],
    191: [
        ("Y reuniré", [0]),
        ("a todas", [1, 2]),
        ("las naciones", [3]),
        ("a Jerusalén", [4, 5]),
        ("para la batalla", [6]),
        ("y será tomada", [7]),
        ("la ciudad", [8]),
        ("y serán saqueadas", [9]),
        ("las casas", [10]),
        ("y las mujeres", [11]),
        ("serán violadas", [12]),
        ("y saldrá", [13]),
        ("la mitad", [14]),
        ("de la ciudad", [15]),
        ("al cautiverio", [16]),
        ("y el resto", [17]),
        ("del pueblo", [18]),
        ("no", [19]),
        ("será cortado", [20]),
        ("de la ciudad", [21, 22]),
    ],
    192: [
        ("Y saldrá", [0]),
        ("Jehová", [1]),
        ("y peleará", [2]),
        ("con aquellas naciones", [3, 4]),
        ("como día", [5]),
        ("de su pelear", [6]),
        ("en día", [7]),
        ("de batalla", [8]),
    ],
    193: [
        ("Y estarán de pie", [0]),
        ("sus pies", [1]),
        ("en aquel día", [2, 3]),
        ("sobre", [4]),
        ("el monte", [5]),
        ("de los olivos", [6]),
        ("que", [7]),
        ("está sobre", [8]),
        ("la faz", [9]),
        ("de Jerusalén", [10]),
        ("desde el oriente", [11]),
        ("y se partirá", [12]),
        ("el monte", [13]),
        ("de los olivos", [14]),
        ("desde su mitad", [15]),
        ("hacia el oriente", [16]),
        ("y hacia el mar", [17]),
        ("un valle", [18]),
        ("muy", [20]),
        ("grande", [19]),
        ("y se apartará", [21]),
        ("la mitad", [22]),
        ("del monte", [23]),
        ("hacia el norte", [24]),
        ("y su mitad", [25]),
        ("hacia el sur", [26]),
    ],
    194: [
        ("Y huirán ustedes", [0]),
        ("el valle", [1]),
        ("de mis montes", [2]),
        ("porque", [3]),
        ("llegará", [4]),
        ("el valle", [5]),
        ("de los montes", [6]),
        ("hasta", [7]),
        ("Azal", [8]),
        ("y huirán ustedes", [9]),
        ("como", [10]),
        ("huyeron ustedes", [11]),
        ("de delante", [12]),
        ("del terremoto", [13]),
        ("en los días", [14]),
        ("de Uzías", [15]),
        ("rey", [16]),
        ("de Judá", [17]),
        ("Y vendrá", [18]),
        ("Jehová", [19]),
        ("mi Dios", [20]),
        ("todos", [21]),
        ("los santos", [22]),
        ("contigo", [23]),
    ],
    195: [
        ("Y será", [0]),
        ("en aquel día", [1, 2]),
        ("no", [3]),
        ("habrá", [4]),
        ("luz", [5]),
        ("preciosas", [6]),
        ("se congelarán", [7]),
    ],
    196: [
        ("Y será", [0]),
        ("un día", [1]),
        ("uno", [2]),
        ("él", [3]),
        ("será conocido", [4]),
        ("a Jehová", [5]),
        ("no", [6]),
        ("día", [7]),
        ("y no", [8]),
        ("noche", [9]),
        ("y será", [10]),
        ("a tiempo", [11]),
        ("de tarde", [12]),
        ("habrá", [13]),
        ("luz", [14]),
    ],
    197: [
        ("Y será", [0]),
        ("en aquel día", [1, 2]),
        ("saldrán", [3]),
        ("aguas", [4]),
        ("vivas", [5]),
        ("de Jerusalén", [6]),
        ("su mitad", [7]),
        ("al mar", [8, 9]),
        ("oriental", [10]),
        ("y su mitad", [11]),
        ("al mar", [12, 13]),
        ("occidental", [14]),
        ("en el verano", [15]),
        ("y en el invierno", [16]),
        ("será", [17]),
    ],
    198: [
        ("Y será", [0]),
        ("Jehová", [1]),
        ("por rey", [2]),
        ("sobre", [3]),
        ("toda", [4]),
        ("la tierra", [5]),
        ("En aquel día", [6, 7]),
        ("será", [8]),
        ("Jehová", [9]),
        ("uno", [10]),
        ("y su nombre", [11]),
        ("uno", [12]),
    ],
    199: [
        ("Se volverá", [0]),
        ("toda", [1]),
        ("la tierra", [2]),
        ("como la Arabá", [3]),
        ("desde Geba", [4]),
        ("hasta Rimón", [5]),
        ("sur", [6]),
        ("de Jerusalén", [7]),
        ("y será exaltada", [8]),
        ("y habitará", [9]),
        ("debajo de ella", [10]),
        ("desde la puerta", [11]),
        ("de Benjamín", [12]),
        ("hasta", [13]),
        ("el lugar", [14]),
        ("de la puerta", [15]),
        ("primera", [16]),
        ("hasta", [17]),
        ("la puerta", [18]),
        ("de las esquinas", [19]),
        ("y la torre", [20]),
        ("de Hananeel", [21]),
        ("hasta", [22]),
        ("los lagares", [23]),
        ("del rey", [24]),
    ],
    200: [
        ("Y habitarán", [0]),
        ("en ella", [1]),
        ("y no habrá más anatema", [2, 3, 4, 5]),
        ("y habitará", [6]),
        ("Jerusalén", [7]),
        ("en seguridad", [8]),
    ],
    201: [
        ("Y esta", [0]),
        ("será", [1]),
        ("la plaga", [2]),
        ("con que", [3]),
        ("herirá", [4]),
        ("Jehová", [5]),
        ("a todos", [6, 7]),
        ("los pueblos", [8]),
        ("que", [9]),
        ("guerrearon", [10]),
        ("sobre", [11]),
        ("Jerusalén", [12]),
        ("pudriéndose", [13]),
        ("su carne", [14]),
        ("y él", [15]),
        ("de pie", [16]),
        ("sobre", [17]),
        ("sus pies", [18]),
        ("y sus ojos", [19]),
        ("se pudrirán", [20]),
        ("en las cuencas de ellas", [21]),
        ("y su lengua", [22]),
        ("se pudrirá", [23]),
        ("en la boca de ellos", [24]),
    ],
    202: [
        ("Y será", [0]),
        ("en aquel día", [1, 2]),
        ("habrá", [3]),
        ("pánico", [4]),
        ("de Jehová", [5]),
        ("grande", [6]),
        ("en ellos", [7]),
        ("y asirá", [8]),
        ("cada uno", [9]),
        ("la mano", [10]),
        ("de su prójimo", [11]),
        ("y subirá", [12]),
        ("su mano", [13]),
        ("sobre", [14]),
        ("la mano", [15]),
        ("de su prójimo", [16]),
    ],
    203: [
        ("Y también", [0]),
        ("Judá", [1]),
        ("peleará", [2]),
        ("en Jerusalén", [3]),
        ("y será reunida", [4]),
        ("la riqueza", [5]),
        ("de todas", [6]),
        ("las naciones", [7]),
        ("en derredor", [8]),
        ("oro", [9]),
        ("y plata", [10]),
        ("y vestidos", [11]),
        ("a abundancia", [12]),
        ("mucho", [13]),
    ],
    204: [
        ("Y así", [0]),
        ("será", [1]),
        ("la plaga", [2]),
        ("del caballo", [3]),
        ("el mulo", [4]),
        ("el camello", [5]),
        ("y el asno", [6]),
        ("y de toda", [7]),
        ("bestia", [8]),
        ("que", [9]),
        ("haya", [10]),
        ("en aquellos campamentos", [11, 12]),
        ("como esta plaga", [13, 14]),
    ],
    205: [
        ("Y será", [0]),
        ("todo", [1]),
        ("el restante", [2]),
        ("de todas", [3]),
        ("las naciones", [4]),
        ("que vienen", [5]),
        ("sobre", [6]),
        ("Jerusalén", [7]),
        ("y subirán", [8]),
        ("de año", [9, 10]),
        ("en año", [11]),
        ("para postrarse", [12]),
        ("al rey", [13]),
        ("Jehová", [14]),
        ("de los ejércitos", [15]),
        ("y para celebrar", [16]),
        ("la fiesta", [17, 18]),
        ("de las cabañas", [19]),
    ],
    206: [
        ("Y será", [0]),
        ("el que", [1]),
        ("no", [2]),
        ("suba", [3]),
        ("de las familias", [4, 5]),
        ("de la tierra", [6]),
        ("a Jerusalén", [7, 8]),
        ("para postrarse", [9]),
        ("al rey", [10]),
        ("Jehová", [11]),
        ("de los ejércitos", [12]),
        ("y no", [13]),
        ("sobre ellos", [14]),
        ("será", [15]),
        ("la lluvia", [16]),
    ],
    207: [
        ("Y si", [0]),
        ("la familia", [1]),
        ("de Egipto", [2]),
        ("no", [3]),
        ("sube", [4]),
        ("y no", [5]),
        ("viene", [6]),
        ("y no", [7]),
        ("sobre ellos", [8]),
        ("será", [9]),
        ("la plaga", [10]),
        ("con que", [11]),
        ("herirá", [12]),
        ("Jehová", [13]),
        ("a las naciones", [14, 15]),
        ("que", [16]),
        ("no", [17]),
        ("suban", [18]),
        ("a celebrar", [19]),
        ("la fiesta", [20, 21]),
        ("de las cabañas", [22]),
    ],
    208: [
        ("Esto", [0]),
        ("será", [1]),
        ("el pecado", [2]),
        ("de Egipto", [3]),
        ("y el pecado", [4]),
        ("de todas", [5]),
        ("las naciones", [6]),
        ("que", [7]),
        ("no", [8]),
        ("suban", [9]),
        ("a celebrar", [10]),
        ("la fiesta", [11, 12]),
        ("de las cabañas", [13]),
    ],
    209: [
        ("En aquel día", [0, 1]),
        ("habrá", [2]),
        ("sobre", [3]),
        ("las campanillas", [4]),
        ("del caballo", [5]),
        ("santidad", [6]),
        ("para Jehová", [7]),
        ("y serán", [8]),
        ("las ollas", [9]),
        ("en la casa", [10]),
        ("de Jehová", [11]),
        ("como los tazones", [12]),
        ("delante", [13]),
        ("del altar", [14]),
    ],
    210: [
        ("Y será", [0]),
        ("toda", [1]),
        ("olla", [2]),
        ("en Jerusalén", [3]),
        ("y en Judá", [4]),
        ("santidad", [5]),
        ("para Jehová", [6]),
        ("de los ejércitos", [7]),
        ("y vendrán", [8]),
        ("todos", [9]),
        ("los que sacrifican", [10]),
        ("y tomarán", [11]),
        ("de ellos", [12]),
        ("y cocerán", [13]),
        ("en ellos", [14]),
        ("y no", [15]),
        ("habrá", [16]),
        ("cananeo", [17]),
        ("más", [18]),
        ("en la casa", [19]),
        ("de Jehová", [20]),
        ("de los ejércitos", [21]),
        ("en aquel día", [22, 23]),
    ],
}


def find_surface(spanish: str, needle: str, cursor: int) -> tuple[int, int]:
    pos = spanish.find(needle, cursor)
    if pos < 0:
        raise ValueError(f"surface not found from {cursor}: {needle!r} in {spanish!r}")
    return pos, pos + len(needle)


def units_for(phrase: dict, hand: list[tuple[str, list[int]]]) -> list[dict]:
    spanish = phrase["spanish"]
    rows = phrase["tokenRows"]
    cursor = 0
    raw: list[tuple[int, int, list[int]]] = []
    for surface, indexes in hand:
        start, end = find_surface(spanish, surface, cursor)
        for i in indexes:
            if i < 0 or i >= len(rows):
                raise ValueError(f"{phrase['reference']} bad row {i} (n={len(rows)})")
        raw.append((start, end, indexes))
        cursor = end
    units = []
    for u, (start, end, indexes) in enumerate(raw):
        span_start = 0 if u == 0 else start
        span_end = raw[u + 1][0] if u + 1 < len(raw) else len(spanish)
        ids = [rows[i]["sourceTokenId"] for i in indexes]
        units.append(
            {
                "unitId": f"{phrase['phraseIndex']}:{u}",
                "surface": spanish[span_start:span_end],
                "charStart": span_start,
                "charEnd": span_end,
                "sourceTokenIds": ids,
                "method": "hand",
            }
        )
    return units


def main() -> None:
    phrases = json.loads(PHRASES.read_text(encoding="utf-8"))
    links = []
    errors: list[str] = []
    hand_n = 0
    unwalked_n = 0
    for p in phrases:
        idx = p["phraseIndex"]
        if idx in HAND:
            try:
                units = units_for(p, HAND[idx])
            except ValueError as e:
                errors.append(str(e))
                continue
            linked: set[str] = set()
            for u in units:
                linked.update(u["sourceTokenIds"])
            missing = [r["sourceTokenId"] + " " + r["surface"] for r in p["tokenRows"] if r["sourceTokenId"] not in linked]
            extra = linked - set(p["sourceTokenIds"])
            if missing:
                errors.append(f"{p['reference']} uncovered: {missing}")
            if extra:
                errors.append(f"{p['reference']} extra ids: {sorted(extra)}")
            covered = "".join(u["surface"] for u in units)
            if covered != p["spanish"]:
                errors.append(f"{p['reference']} spanish gap: {covered!r} != {p['spanish']!r}")
            links.append(
                {
                    "phraseIndex": idx,
                    "reference": p["reference"],
                    "status": "seeded-hand",
                    "units": units,
                }
            )
            hand_n += 1
        else:
            links.append(
                {
                    "phraseIndex": idx,
                    "reference": p["reference"],
                    "status": "unwalked",
                    "units": [],
                }
            )
            unwalked_n += 1
    if errors:
        print("SEED FAILED", file=sys.stderr)
        for e in errors:
            print(e, file=sys.stderr)
        sys.exit(1)
    doc = {
        "bookId": "zacarias",
        "textualBasis": "OSHB/WLC",
        "schemaVersion": 1,
        "numbering": "protestant",
        "links": links,
    }
    OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"hand={hand_n} unwalked={unwalked_n} wrote {OUT}")


if __name__ == "__main__":
    main()
